package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcsLg generated by hbm2java
 */
@Entity
@Table(name="acs_lg"
)
public class AcsLg  implements java.io.Serializable {


     private AcsLgId id;
     private Srvc srvc;
     private Acs acs;
     private DbSts dbSts;
     private Rl rl;
     private UsrGrp usrGrp;
     private Sn sn;
     private short objTp;
     private Integer obj;

    public AcsLg() {
    }

	
    public AcsLg(AcsLgId id, Srvc srvc, Acs acs, DbSts dbSts, Rl rl, UsrGrp usrGrp, Sn sn, short objTp) {
        this.id = id;
        this.srvc = srvc;
        this.acs = acs;
        this.dbSts = dbSts;
        this.rl = rl;
        this.usrGrp = usrGrp;
        this.sn = sn;
        this.objTp = objTp;
    }
    public AcsLg(AcsLgId id, Srvc srvc, Acs acs, DbSts dbSts, Rl rl, UsrGrp usrGrp, Sn sn, short objTp, Integer obj) {
       this.id = id;
       this.srvc = srvc;
       this.acs = acs;
       this.dbSts = dbSts;
       this.rl = rl;
       this.usrGrp = usrGrp;
       this.sn = sn;
       this.objTp = objTp;
       this.obj = obj;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idLg", column=@Column(name="id_lg", nullable=false) ), 
        @AttributeOverride(name="ts", column=@Column(name="ts", nullable=false, length=29) ) } )
    public AcsLgId getId() {
        return this.id;
    }
    
    public void setId(AcsLgId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="srvc", nullable=false)
    public Srvc getSrvc() {
        return this.srvc;
    }
    
    public void setSrvc(Srvc srvc) {
        this.srvc = srvc;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_acs", nullable=false)
    public Acs getAcs() {
        return this.acs;
    }
    
    public void setAcs(Acs acs) {
        this.acs = acs;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rl", nullable=false)
    public Rl getRl() {
        return this.rl;
    }
    
    public void setRl(Rl rl) {
        this.rl = rl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usr_grp", nullable=false)
    public UsrGrp getUsrGrp() {
        return this.usrGrp;
    }
    
    public void setUsrGrp(UsrGrp usrGrp) {
        this.usrGrp = usrGrp;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sn", nullable=false)
    public Sn getSn() {
        return this.sn;
    }
    
    public void setSn(Sn sn) {
        this.sn = sn;
    }
    
    @Column(name="obj_tp", nullable=false)
    public short getObjTp() {
        return this.objTp;
    }
    
    public void setObjTp(short objTp) {
        this.objTp = objTp;
    }
    
    @Column(name="obj")
    public Integer getObj() {
        return this.obj;
    }
    
    public void setObj(Integer obj) {
        this.obj = obj;
    }




}


