package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActiveEntity generated by hbm2java
 */
@Entity
@Table(name="active_entity"
)
public class ActiveEntity  implements java.io.Serializable {


     private ActiveEntityId id;
     private Submodel submodel;
     private EntitySpec entitySpec;
     private Character activityStatus;

    public ActiveEntity() {
    }

	
    public ActiveEntity(ActiveEntityId id, Submodel submodel, EntitySpec entitySpec) {
        this.id = id;
        this.submodel = submodel;
        this.entitySpec = entitySpec;
    }
    public ActiveEntity(ActiveEntityId id, Submodel submodel, EntitySpec entitySpec, Character activityStatus) {
       this.id = id;
       this.submodel = submodel;
       this.entitySpec = entitySpec;
       this.activityStatus = activityStatus;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idModel", column=@Column(name="id_model", nullable=false) ), 
        @AttributeOverride(name="idSubmodel", column=@Column(name="id_submodel", nullable=false) ), 
        @AttributeOverride(name="idEntitySpec", column=@Column(name="id_entity_spec", nullable=false) ) } )
    public ActiveEntityId getId() {
        return this.id;
    }
    
    public void setId(ActiveEntityId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="id_model", referencedColumnName="id_model", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="id_submodel", referencedColumnName="id_submodel", nullable=false, insertable=false, updatable=false) } )
    public Submodel getSubmodel() {
        return this.submodel;
    }
    
    public void setSubmodel(Submodel submodel) {
        this.submodel = submodel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_entity_spec", nullable=false, insertable=false, updatable=false)
    public EntitySpec getEntitySpec() {
        return this.entitySpec;
    }
    
    public void setEntitySpec(EntitySpec entitySpec) {
        this.entitySpec = entitySpec;
    }
    
    @Column(name="activity_status", length=1)
    public Character getActivityStatus() {
        return this.activityStatus;
    }
    
    public void setActivityStatus(Character activityStatus) {
        this.activityStatus = activityStatus;
    }




}


