package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActiveSetId generated by hbm2java
 */
@Embeddable
public class ActiveSetId  implements java.io.Serializable {


     private int idModel;
     private int idSubmodel;
     private int idSetSpec;

    public ActiveSetId() {
    }

    public ActiveSetId(int idModel, int idSubmodel, int idSetSpec) {
       this.idModel = idModel;
       this.idSubmodel = idSubmodel;
       this.idSetSpec = idSetSpec;
    }
   

    @Column(name="id_model", nullable=false)
    public int getIdModel() {
        return this.idModel;
    }
    
    public void setIdModel(int idModel) {
        this.idModel = idModel;
    }

    @Column(name="id_submodel", nullable=false)
    public int getIdSubmodel() {
        return this.idSubmodel;
    }
    
    public void setIdSubmodel(int idSubmodel) {
        this.idSubmodel = idSubmodel;
    }

    @Column(name="id_set_spec", nullable=false)
    public int getIdSetSpec() {
        return this.idSetSpec;
    }
    
    public void setIdSetSpec(int idSetSpec) {
        this.idSetSpec = idSetSpec;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ActiveSetId) ) return false;
		 ActiveSetId castOther = ( ActiveSetId ) other; 
         
		 return (this.getIdModel()==castOther.getIdModel())
 && (this.getIdSubmodel()==castOther.getIdSubmodel())
 && (this.getIdSetSpec()==castOther.getIdSetSpec());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdModel();
         result = 37 * result + this.getIdSubmodel();
         result = 37 * result + this.getIdSetSpec();
         return result;
   }   


}


