package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActiveSet generated by hbm2java
 */
@Entity
@Table(name="active_set"
)
public class ActiveSet  implements java.io.Serializable {


     private ActiveSetId id;
     private Submodel submodel;
     private SetSpec setSpec;
     private Character activityStatus;

    public ActiveSet() {
    }

	
    public ActiveSet(ActiveSetId id, Submodel submodel, SetSpec setSpec) {
        this.id = id;
        this.submodel = submodel;
        this.setSpec = setSpec;
    }
    public ActiveSet(ActiveSetId id, Submodel submodel, SetSpec setSpec, Character activityStatus) {
       this.id = id;
       this.submodel = submodel;
       this.setSpec = setSpec;
       this.activityStatus = activityStatus;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idModel", column=@Column(name="id_model", nullable=false) ), 
        @AttributeOverride(name="idSubmodel", column=@Column(name="id_submodel", nullable=false) ), 
        @AttributeOverride(name="idSetSpec", column=@Column(name="id_set_spec", nullable=false) ) } )
    public ActiveSetId getId() {
        return this.id;
    }
    
    public void setId(ActiveSetId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="id_model", referencedColumnName="id_model", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="id_submodel", referencedColumnName="id_submodel", nullable=false, insertable=false, updatable=false) } )
    public Submodel getSubmodel() {
        return this.submodel;
    }
    
    public void setSubmodel(Submodel submodel) {
        this.submodel = submodel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_set_spec", nullable=false, insertable=false, updatable=false)
    public SetSpec getSetSpec() {
        return this.setSpec;
    }
    
    public void setSetSpec(SetSpec setSpec) {
        this.setSpec = setSpec;
    }
    
    @Column(name="activity_status", length=1)
    public Character getActivityStatus() {
        return this.activityStatus;
    }
    
    public void setActivityStatus(Character activityStatus) {
        this.activityStatus = activityStatus;
    }




}


