package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AnalysisType generated by hbm2java
 */
@Entity
@Table(name="analysis_type"
)
public class AnalysisType  implements java.io.Serializable {


     private int idAnalysisType;
     private String analysisTypeName;
     private Set<ModelAnalysis> modelAnalysises = new HashSet<ModelAnalysis>(0);

    public AnalysisType() {
    }

	
    public AnalysisType(int idAnalysisType, String analysisTypeName) {
        this.idAnalysisType = idAnalysisType;
        this.analysisTypeName = analysisTypeName;
    }
    public AnalysisType(int idAnalysisType, String analysisTypeName, Set<ModelAnalysis> modelAnalysises) {
       this.idAnalysisType = idAnalysisType;
       this.analysisTypeName = analysisTypeName;
       this.modelAnalysises = modelAnalysises;
    }
   
     @Id 
    
    @Column(name="id_analysis_type", unique=true, nullable=false)
    public int getIdAnalysisType() {
        return this.idAnalysisType;
    }
    
    public void setIdAnalysisType(int idAnalysisType) {
        this.idAnalysisType = idAnalysisType;
    }
    
    @Column(name="analysis_type_name", nullable=false, length=20)
    public String getAnalysisTypeName() {
        return this.analysisTypeName;
    }
    
    public void setAnalysisTypeName(String analysisTypeName) {
        this.analysisTypeName = analysisTypeName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="analysisType")
    public Set<ModelAnalysis> getModelAnalysises() {
        return this.modelAnalysises;
    }
    
    public void setModelAnalysises(Set<ModelAnalysis> modelAnalysises) {
        this.modelAnalysises = modelAnalysises;
    }




}


