package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppInstance generated by hbm2java
 */
@Entity
@Table(name="app_instance"
)
public class AppInstance  implements java.io.Serializable {


     private int id;
     private Integer srcRevision;
     private Integer dbStructureVersion;
     private Date dbStructureCreated;
     private Date installersRun;
     private String installationType;

    public AppInstance() {
    }

	
    public AppInstance(int id) {
        this.id = id;
    }
    public AppInstance(int id, Integer srcRevision, Integer dbStructureVersion, Date dbStructureCreated, Date installersRun, String installationType) {
       this.id = id;
       this.srcRevision = srcRevision;
       this.dbStructureVersion = dbStructureVersion;
       this.dbStructureCreated = dbStructureCreated;
       this.installersRun = installersRun;
       this.installationType = installationType;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="src_revision")
    public Integer getSrcRevision() {
        return this.srcRevision;
    }
    
    public void setSrcRevision(Integer srcRevision) {
        this.srcRevision = srcRevision;
    }
    
    @Column(name="db_structure_version")
    public Integer getDbStructureVersion() {
        return this.dbStructureVersion;
    }
    
    public void setDbStructureVersion(Integer dbStructureVersion) {
        this.dbStructureVersion = dbStructureVersion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="db_structure_created", length=29)
    public Date getDbStructureCreated() {
        return this.dbStructureCreated;
    }
    
    public void setDbStructureCreated(Date dbStructureCreated) {
        this.dbStructureCreated = dbStructureCreated;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="installers_run", length=29)
    public Date getInstallersRun() {
        return this.installersRun;
    }
    
    public void setInstallersRun(Date installersRun) {
        this.installersRun = installersRun;
    }
    
    @Column(name="installation_type", length=20)
    public String getInstallationType() {
        return this.installationType;
    }
    
    public void setInstallationType(String installationType) {
        this.installationType = installationType;
    }




}


