package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Athntctn generated by hbm2java
 */
@Entity
@Table(name="athntctn"
)
public class Athntctn  implements java.io.Serializable {


     private short idAthntctn;
     private DbSts dbSts;
     private Lbl lbl;
     private Set<AthntctnUsr> athntctnUsrs = new HashSet<AthntctnUsr>(0);
     private Set<UsrLg> usrLgs = new HashSet<UsrLg>(0);
     private Set<Usr> usrs = new HashSet<Usr>(0);

    public Athntctn() {
    }

	
    public Athntctn(short idAthntctn, DbSts dbSts, Lbl lbl) {
        this.idAthntctn = idAthntctn;
        this.dbSts = dbSts;
        this.lbl = lbl;
    }
    public Athntctn(short idAthntctn, DbSts dbSts, Lbl lbl, Set<AthntctnUsr> athntctnUsrs, Set<UsrLg> usrLgs, Set<Usr> usrs) {
       this.idAthntctn = idAthntctn;
       this.dbSts = dbSts;
       this.lbl = lbl;
       this.athntctnUsrs = athntctnUsrs;
       this.usrLgs = usrLgs;
       this.usrs = usrs;
    }
   
     @Id 
    
    @Column(name="id_athntctn", unique=true, nullable=false)
    public short getIdAthntctn() {
        return this.idAthntctn;
    }
    
    public void setIdAthntctn(short idAthntctn) {
        this.idAthntctn = idAthntctn;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_lbl", nullable=false)
    public Lbl getLbl() {
        return this.lbl;
    }
    
    public void setLbl(Lbl lbl) {
        this.lbl = lbl;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="athntctn")
    public Set<AthntctnUsr> getAthntctnUsrs() {
        return this.athntctnUsrs;
    }
    
    public void setAthntctnUsrs(Set<AthntctnUsr> athntctnUsrs) {
        this.athntctnUsrs = athntctnUsrs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="athntctn")
    public Set<UsrLg> getUsrLgs() {
        return this.usrLgs;
    }
    
    public void setUsrLgs(Set<UsrLg> usrLgs) {
        this.usrLgs = usrLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="athntctn")
    public Set<Usr> getUsrs() {
        return this.usrs;
    }
    
    public void setUsrs(Set<Usr> usrs) {
        this.usrs = usrs;
    }




}


