package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AthntctnUsrId generated by hbm2java
 */
@Embeddable
public class AthntctnUsrId  implements java.io.Serializable {


     private short idAthntctn;
     private int idUsr;

    public AthntctnUsrId() {
    }

    public AthntctnUsrId(short idAthntctn, int idUsr) {
       this.idAthntctn = idAthntctn;
       this.idUsr = idUsr;
    }
   

    @Column(name="id_athntctn", nullable=false)
    public short getIdAthntctn() {
        return this.idAthntctn;
    }
    
    public void setIdAthntctn(short idAthntctn) {
        this.idAthntctn = idAthntctn;
    }

    @Column(name="id_usr", nullable=false)
    public int getIdUsr() {
        return this.idUsr;
    }
    
    public void setIdUsr(int idUsr) {
        this.idUsr = idUsr;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AthntctnUsrId) ) return false;
		 AthntctnUsrId castOther = ( AthntctnUsrId ) other; 
         
		 return (this.getIdAthntctn()==castOther.getIdAthntctn())
 && (this.getIdUsr()==castOther.getIdUsr());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdAthntctn();
         result = 37 * result + this.getIdUsr();
         return result;
   }   


}


