package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AthntctnUsrLg generated by hbm2java
 */
@Entity
@Table(name="athntctn_usr_lg"
)
public class AthntctnUsrLg  implements java.io.Serializable {


     private AthntctnUsrLgId id;
     private short srvc;
     private short idSrvc;
     private short idAthntctn;
     private int idUsr;
     private String password;
     private String username;
     private char dbSts;
     private String sn;

    public AthntctnUsrLg() {
    }

	
    public AthntctnUsrLg(AthntctnUsrLgId id, short srvc, short idSrvc, short idAthntctn, int idUsr, char dbSts, String sn) {
        this.id = id;
        this.srvc = srvc;
        this.idSrvc = idSrvc;
        this.idAthntctn = idAthntctn;
        this.idUsr = idUsr;
        this.dbSts = dbSts;
        this.sn = sn;
    }
    public AthntctnUsrLg(AthntctnUsrLgId id, short srvc, short idSrvc, short idAthntctn, int idUsr, String password, String username, char dbSts, String sn) {
       this.id = id;
       this.srvc = srvc;
       this.idSrvc = idSrvc;
       this.idAthntctn = idAthntctn;
       this.idUsr = idUsr;
       this.password = password;
       this.username = username;
       this.dbSts = dbSts;
       this.sn = sn;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idLg", column=@Column(name="id_lg", nullable=false) ), 
        @AttributeOverride(name="ts", column=@Column(name="ts", nullable=false, length=29) ) } )
    public AthntctnUsrLgId getId() {
        return this.id;
    }
    
    public void setId(AthntctnUsrLgId id) {
        this.id = id;
    }
    
    @Column(name="srvc", nullable=false)
    public short getSrvc() {
        return this.srvc;
    }
    
    public void setSrvc(short srvc) {
        this.srvc = srvc;
    }
    
    @Column(name="id_srvc", nullable=false)
    public short getIdSrvc() {
        return this.idSrvc;
    }
    
    public void setIdSrvc(short idSrvc) {
        this.idSrvc = idSrvc;
    }
    
    @Column(name="id_athntctn", nullable=false)
    public short getIdAthntctn() {
        return this.idAthntctn;
    }
    
    public void setIdAthntctn(short idAthntctn) {
        this.idAthntctn = idAthntctn;
    }
    
    @Column(name="id_usr", nullable=false)
    public int getIdUsr() {
        return this.idUsr;
    }
    
    public void setIdUsr(int idUsr) {
        this.idUsr = idUsr;
    }
    
    @Column(name="password", length=64)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="username", length=64)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="db_sts", nullable=false, length=1)
    public char getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(char dbSts) {
        this.dbSts = dbSts;
    }
    
    @Column(name="sn", nullable=false, length=256)
    public String getSn() {
        return this.sn;
    }
    
    public void setSn(String sn) {
        this.sn = sn;
    }




}


