package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AthntctnUsr generated by hbm2java
 */
@Entity
@Table(name="athntctn_usr"
    , uniqueConstraints = @UniqueConstraint(columnNames={"id_usr", "id_athntctn"}) 
)
public class AthntctnUsr  implements java.io.Serializable {


     private AthntctnUsrId id;
     private Usr usr;
     private DbSts dbSts;
     private Athntctn athntctn;
     private Sn sn;
     private String username;
     private String password;

    public AthntctnUsr() {
    }

	
    public AthntctnUsr(AthntctnUsrId id, Usr usr, DbSts dbSts, Athntctn athntctn, Sn sn) {
        this.id = id;
        this.usr = usr;
        this.dbSts = dbSts;
        this.athntctn = athntctn;
        this.sn = sn;
    }
    public AthntctnUsr(AthntctnUsrId id, Usr usr, DbSts dbSts, Athntctn athntctn, Sn sn, String username, String password) {
       this.id = id;
       this.usr = usr;
       this.dbSts = dbSts;
       this.athntctn = athntctn;
       this.sn = sn;
       this.username = username;
       this.password = password;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idAthntctn", column=@Column(name="id_athntctn", nullable=false) ), 
        @AttributeOverride(name="idUsr", column=@Column(name="id_usr", nullable=false) ) } )
    public AthntctnUsrId getId() {
        return this.id;
    }
    
    public void setId(AthntctnUsrId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usr", nullable=false, insertable=false, updatable=false)
    public Usr getUsr() {
        return this.usr;
    }
    
    public void setUsr(Usr usr) {
        this.usr = usr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_athntctn", nullable=false, insertable=false, updatable=false)
    public Athntctn getAthntctn() {
        return this.athntctn;
    }
    
    public void setAthntctn(Athntctn athntctn) {
        this.athntctn = athntctn;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sn", nullable=false)
    public Sn getSn() {
        return this.sn;
    }
    
    public void setSn(Sn sn) {
        this.sn = sn;
    }
    
    @Column(name="username", length=64)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="password", length=64)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


