package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cntr generated by hbm2java
 */
@Entity
@Table(name="cntr"
)
public class Cntr  implements java.io.Serializable {


     private String idCntr;
     private DbSts dbSts;
     private Set<Lcl> lcls = new HashSet<Lcl>(0);

    public Cntr() {
    }

	
    public Cntr(String idCntr, DbSts dbSts) {
        this.idCntr = idCntr;
        this.dbSts = dbSts;
    }
    public Cntr(String idCntr, DbSts dbSts, Set<Lcl> lcls) {
       this.idCntr = idCntr;
       this.dbSts = dbSts;
       this.lcls = lcls;
    }
   
     @Id 
    
    @Column(name="id_cntr", unique=true, nullable=false, length=2)
    public String getIdCntr() {
        return this.idCntr;
    }
    
    public void setIdCntr(String idCntr) {
        this.idCntr = idCntr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="cntr")
    public Set<Lcl> getLcls() {
        return this.lcls;
    }
    
    public void setLcls(Set<Lcl> lcls) {
        this.lcls = lcls;
    }




}


