package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name="comments"
)
public class Comments  implements java.io.Serializable {


     private String idComment;
     private Submodel submodel;
     private ModelSpecRev modelSpecRev;
     private ModelDataUpdate modelDataUpdate;
     private Model model;
     private String commentStr;

    public Comments() {
    }

    public Comments(Submodel submodel, ModelSpecRev modelSpecRev, ModelDataUpdate modelDataUpdate, Model model, String commentStr) {
       this.submodel = submodel;
       this.modelSpecRev = modelSpecRev;
       this.modelDataUpdate = modelDataUpdate;
       this.model = model;
       this.commentStr = commentStr;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__JPA_COMMENTS__ID_JPA_COMMENTS")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_comment", unique=true, nullable=false, length=18)
    public String getIdComment() {
        return this.idComment;
    }
    
    public void setIdComment(String idComment) {
        this.idComment = idComment;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="id_model", referencedColumnName="id_model"), 
        @JoinColumn(name="id_submodel", referencedColumnName="id_submodel") } )
    public Submodel getSubmodel() {
        return this.submodel;
    }
    
    public void setSubmodel(Submodel submodel) {
        this.submodel = submodel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_spec_rev")
    public ModelSpecRev getModelSpecRev() {
        return this.modelSpecRev;
    }
    
    public void setModelSpecRev(ModelSpecRev modelSpecRev) {
        this.modelSpecRev = modelSpecRev;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_update")
    public ModelDataUpdate getModelDataUpdate() {
        return this.modelDataUpdate;
    }
    
    public void setModelDataUpdate(ModelDataUpdate modelDataUpdate) {
        this.modelDataUpdate = modelDataUpdate;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_model", insertable=false, updatable=false)
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }
    
    @Column(name="comment_str", length=1000)
    public String getCommentStr() {
        return this.commentStr;
    }
    
    public void setCommentStr(String commentStr) {
        this.commentStr = commentStr;
    }




}


