package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComputationalTask generated by hbm2java
 */
@Entity
@Table(name="computational_task"
)
public class ComputationalTask  implements java.io.Serializable {


     private Integer idTask;
     private ModelAnalysis modelAnalysis;
     private Host host;
     private Solver solver;
     private Usr usr;
     private ResultsStorageType resultsStorageType;
     private Date creationDate;
     private String shortDesc;
     private String longDesc;

    public ComputationalTask() {
    }

	
    public ComputationalTask(Usr usr, Date creationDate) {
        this.usr = usr;
        this.creationDate = creationDate;
    }
    public ComputationalTask(ModelAnalysis modelAnalysis, Host host, Solver solver, Usr usr, ResultsStorageType resultsStorageType, Date creationDate, String shortDesc, String longDesc) {
       this.modelAnalysis = modelAnalysis;
       this.host = host;
       this.solver = solver;
       this.usr = usr;
       this.resultsStorageType = resultsStorageType;
       this.creationDate = creationDate;
       this.shortDesc = shortDesc;
       this.longDesc = longDesc;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__JPA_COMPUTATIONAL_TASK__ID_JPA_COMPUTATIONAL_TASK")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_task", unique=true, nullable=false)
    public Integer getIdTask() {
        return this.idTask;
    }
    
    public void setIdTask(Integer idTask) {
        this.idTask = idTask;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_analysis")
    public ModelAnalysis getModelAnalysis() {
        return this.modelAnalysis;
    }
    
    public void setModelAnalysis(ModelAnalysis modelAnalysis) {
        this.modelAnalysis = modelAnalysis;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_host")
    public Host getHost() {
        return this.host;
    }
    
    public void setHost(Host host) {
        this.host = host;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_solver")
    public Solver getSolver() {
        return this.solver;
    }
    
    public void setSolver(Solver solver) {
        this.solver = solver;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="created_by", nullable=false)
    public Usr getUsr() {
        return this.usr;
    }
    
    public void setUsr(Usr usr) {
        this.usr = usr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_results_storage")
    public ResultsStorageType getResultsStorageType() {
        return this.resultsStorageType;
    }
    
    public void setResultsStorageType(ResultsStorageType resultsStorageType) {
        this.resultsStorageType = resultsStorageType;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", nullable=false, length=29)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    
    @Column(name="short_desc", length=20)
    public String getShortDesc() {
        return this.shortDesc;
    }
    
    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
    }
    
    @Column(name="long_desc", length=1000)
    public String getLongDesc() {
        return this.longDesc;
    }
    
    public void setLongDesc(String longDesc) {
        this.longDesc = longDesc;
    }




}


