package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DbSts generated by hbm2java
 */
@Entity
@Table(name="db_sts"
)
public class DbSts  implements java.io.Serializable {


     private char idDbSts;
     private Msg msg;
     private Set<MsgLclLg> msgLclLgs = new HashSet<MsgLclLg>(0);
     private Set<MsgLcl> msgLcls = new HashSet<MsgLcl>(0);
     private Set<Lbl> lbls = new HashSet<Lbl>(0);
     private Set<UsrGrp> usrGrps = new HashSet<UsrGrp>(0);
     private Set<Acs> acses = new HashSet<Acs>(0);
     private Set<ModelSpecRev> modelSpecRevs = new HashSet<ModelSpecRev>(0);
     private Set<UsrLg> usrLgs = new HashSet<UsrLg>(0);
     private Set<ModelDataUpdate> modelDataUpdates = new HashSet<ModelDataUpdate>(0);
     private Set<Athntctn> athntctns = new HashSet<Athntctn>(0);
     private Set<Cntr> cntrs = new HashSet<Cntr>(0);
     private Set<AthntctnUsr> athntctnUsrs = new HashSet<AthntctnUsr>(0);
     private Set<LblLcl> lblLcls = new HashSet<LblLcl>(0);
     private Set<LblLg> lblLgs = new HashSet<LblLg>(0);
     private Set<Msg> msgs = new HashSet<Msg>(0);
     private Set<LblLclLg> lblLclLgs = new HashSet<LblLclLg>(0);
     private Set<AcsLg> acsLgs = new HashSet<AcsLg>(0);
     private Set<Lng> lngs = new HashSet<Lng>(0);
     private Set<Usr> usrs = new HashSet<Usr>(0);
     private Set<Lcl> lcls = new HashSet<Lcl>(0);
     private Set<Rl> rls = new HashSet<Rl>(0);
     private Set<UsrGrpLg> usrGrpLgs = new HashSet<UsrGrpLg>(0);
     private Set<UsrGrpGrpLg> usrGrpGrpLgs = new HashSet<UsrGrpGrpLg>(0);
     private Set<UsrGrpGrp> usrGrpGrps = new HashSet<UsrGrpGrp>(0);
     private Set<MsgLg> msgLgs = new HashSet<MsgLg>(0);

    public DbSts() {
    }

	
    public DbSts(char idDbSts) {
        this.idDbSts = idDbSts;
    }
    public DbSts(char idDbSts, Msg msg, Set<MsgLclLg> msgLclLgs, Set<MsgLcl> msgLcls, Set<Lbl> lbls, Set<UsrGrp> usrGrps, Set<Acs> acses, Set<ModelSpecRev> modelSpecRevs, Set<UsrLg> usrLgs, Set<ModelDataUpdate> modelDataUpdates, Set<Athntctn> athntctns, Set<Cntr> cntrs, Set<AthntctnUsr> athntctnUsrs, Set<LblLcl> lblLcls, Set<LblLg> lblLgs, Set<Msg> msgs, Set<LblLclLg> lblLclLgs, Set<AcsLg> acsLgs, Set<Lng> lngs, Set<Usr> usrs, Set<Lcl> lcls, Set<Rl> rls, Set<UsrGrpLg> usrGrpLgs, Set<UsrGrpGrpLg> usrGrpGrpLgs, Set<UsrGrpGrp> usrGrpGrps, Set<MsgLg> msgLgs) {
       this.idDbSts = idDbSts;
       this.msg = msg;
       this.msgLclLgs = msgLclLgs;
       this.msgLcls = msgLcls;
       this.lbls = lbls;
       this.usrGrps = usrGrps;
       this.acses = acses;
       this.modelSpecRevs = modelSpecRevs;
       this.usrLgs = usrLgs;
       this.modelDataUpdates = modelDataUpdates;
       this.athntctns = athntctns;
       this.cntrs = cntrs;
       this.athntctnUsrs = athntctnUsrs;
       this.lblLcls = lblLcls;
       this.lblLgs = lblLgs;
       this.msgs = msgs;
       this.lblLclLgs = lblLclLgs;
       this.acsLgs = acsLgs;
       this.lngs = lngs;
       this.usrs = usrs;
       this.lcls = lcls;
       this.rls = rls;
       this.usrGrpLgs = usrGrpLgs;
       this.usrGrpGrpLgs = usrGrpGrpLgs;
       this.usrGrpGrps = usrGrpGrps;
       this.msgLgs = msgLgs;
    }
   
     @Id 
    
    @Column(name="id_db_sts", unique=true, nullable=false, length=1)
    public char getIdDbSts() {
        return this.idDbSts;
    }
    
    public void setIdDbSts(char idDbSts) {
        this.idDbSts = idDbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="msg")
    public Msg getMsg() {
        return this.msg;
    }
    
    public void setMsg(Msg msg) {
        this.msg = msg;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<MsgLclLg> getMsgLclLgs() {
        return this.msgLclLgs;
    }
    
    public void setMsgLclLgs(Set<MsgLclLg> msgLclLgs) {
        this.msgLclLgs = msgLclLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<MsgLcl> getMsgLcls() {
        return this.msgLcls;
    }
    
    public void setMsgLcls(Set<MsgLcl> msgLcls) {
        this.msgLcls = msgLcls;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<Lbl> getLbls() {
        return this.lbls;
    }
    
    public void setLbls(Set<Lbl> lbls) {
        this.lbls = lbls;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<UsrGrp> getUsrGrps() {
        return this.usrGrps;
    }
    
    public void setUsrGrps(Set<UsrGrp> usrGrps) {
        this.usrGrps = usrGrps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<Acs> getAcses() {
        return this.acses;
    }
    
    public void setAcses(Set<Acs> acses) {
        this.acses = acses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<ModelSpecRev> getModelSpecRevs() {
        return this.modelSpecRevs;
    }
    
    public void setModelSpecRevs(Set<ModelSpecRev> modelSpecRevs) {
        this.modelSpecRevs = modelSpecRevs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<UsrLg> getUsrLgs() {
        return this.usrLgs;
    }
    
    public void setUsrLgs(Set<UsrLg> usrLgs) {
        this.usrLgs = usrLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<ModelDataUpdate> getModelDataUpdates() {
        return this.modelDataUpdates;
    }
    
    public void setModelDataUpdates(Set<ModelDataUpdate> modelDataUpdates) {
        this.modelDataUpdates = modelDataUpdates;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<Athntctn> getAthntctns() {
        return this.athntctns;
    }
    
    public void setAthntctns(Set<Athntctn> athntctns) {
        this.athntctns = athntctns;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<Cntr> getCntrs() {
        return this.cntrs;
    }
    
    public void setCntrs(Set<Cntr> cntrs) {
        this.cntrs = cntrs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<AthntctnUsr> getAthntctnUsrs() {
        return this.athntctnUsrs;
    }
    
    public void setAthntctnUsrs(Set<AthntctnUsr> athntctnUsrs) {
        this.athntctnUsrs = athntctnUsrs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<LblLcl> getLblLcls() {
        return this.lblLcls;
    }
    
    public void setLblLcls(Set<LblLcl> lblLcls) {
        this.lblLcls = lblLcls;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<LblLg> getLblLgs() {
        return this.lblLgs;
    }
    
    public void setLblLgs(Set<LblLg> lblLgs) {
        this.lblLgs = lblLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<Msg> getMsgs() {
        return this.msgs;
    }
    
    public void setMsgs(Set<Msg> msgs) {
        this.msgs = msgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<LblLclLg> getLblLclLgs() {
        return this.lblLclLgs;
    }
    
    public void setLblLclLgs(Set<LblLclLg> lblLclLgs) {
        this.lblLclLgs = lblLclLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<AcsLg> getAcsLgs() {
        return this.acsLgs;
    }
    
    public void setAcsLgs(Set<AcsLg> acsLgs) {
        this.acsLgs = acsLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<Lng> getLngs() {
        return this.lngs;
    }
    
    public void setLngs(Set<Lng> lngs) {
        this.lngs = lngs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<Usr> getUsrs() {
        return this.usrs;
    }
    
    public void setUsrs(Set<Usr> usrs) {
        this.usrs = usrs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<Lcl> getLcls() {
        return this.lcls;
    }
    
    public void setLcls(Set<Lcl> lcls) {
        this.lcls = lcls;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<Rl> getRls() {
        return this.rls;
    }
    
    public void setRls(Set<Rl> rls) {
        this.rls = rls;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<UsrGrpLg> getUsrGrpLgs() {
        return this.usrGrpLgs;
    }
    
    public void setUsrGrpLgs(Set<UsrGrpLg> usrGrpLgs) {
        this.usrGrpLgs = usrGrpLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<UsrGrpGrpLg> getUsrGrpGrpLgs() {
        return this.usrGrpGrpLgs;
    }
    
    public void setUsrGrpGrpLgs(Set<UsrGrpGrpLg> usrGrpGrpLgs) {
        this.usrGrpGrpLgs = usrGrpGrpLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<UsrGrpGrp> getUsrGrpGrps() {
        return this.usrGrpGrps;
    }
    
    public void setUsrGrpGrps(Set<UsrGrpGrp> usrGrpGrps) {
        this.usrGrpGrps = usrGrpGrps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dbSts")
    public Set<MsgLg> getMsgLgs() {
        return this.msgLgs;
    }
    
    public void setMsgLgs(Set<MsgLg> msgLgs) {
        this.msgLgs = msgLgs;
    }




}


