package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EdtSts generated by hbm2java
 */
@Entity
@Table(name="edt_sts"
)
public class EdtSts  implements java.io.Serializable {


     private char idEdtSts;
     private Msg msg;

    public EdtSts() {
    }

	
    public EdtSts(char idEdtSts) {
        this.idEdtSts = idEdtSts;
    }
    public EdtSts(char idEdtSts, Msg msg) {
       this.idEdtSts = idEdtSts;
       this.msg = msg;
    }
   
     @Id 
    
    @Column(name="id_edt_sts", unique=true, nullable=false, length=1)
    public char getIdEdtSts() {
        return this.idEdtSts;
    }
    
    public void setIdEdtSts(char idEdtSts) {
        this.idEdtSts = idEdtSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="msg")
    public Msg getMsg() {
        return this.msg;
    }
    
    public void setMsg(Msg msg) {
        this.msg = msg;
    }




}


