package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * EntityAttrCategoryElement generated by hbm2java
 */
@Entity
@Table(name="entity_attr_category_element"
)
public class EntityAttrCategoryElement  implements java.io.Serializable {


     private Integer idAttrCatEl;
     private EntityAttrCategory entityAttrCategory;
     private int elementNo;
     private Integer code;
     private String value;
     private Set<EntityAttr> entityAttrs = new HashSet<EntityAttr>(0);

    public EntityAttrCategoryElement() {
    }

	
    public EntityAttrCategoryElement(EntityAttrCategory entityAttrCategory, int elementNo, String value) {
        this.entityAttrCategory = entityAttrCategory;
        this.elementNo = elementNo;
        this.value = value;
    }
    public EntityAttrCategoryElement(EntityAttrCategory entityAttrCategory, int elementNo, Integer code, String value, Set<EntityAttr> entityAttrs) {
       this.entityAttrCategory = entityAttrCategory;
       this.elementNo = elementNo;
       this.code = code;
       this.value = value;
       this.entityAttrs = entityAttrs;
    }
   
     @SequenceGenerator(name="generator", sequenceName="seq__jpa_entity_attr_category_element__id_jpa_entity_attr_categ")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_attr_cat_el", unique=true, nullable=false)
    public Integer getIdAttrCatEl() {
        return this.idAttrCatEl;
    }
    
    public void setIdAttrCatEl(Integer idAttrCatEl) {
        this.idAttrCatEl = idAttrCatEl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_category", nullable=false)
    public EntityAttrCategory getEntityAttrCategory() {
        return this.entityAttrCategory;
    }
    
    public void setEntityAttrCategory(EntityAttrCategory entityAttrCategory) {
        this.entityAttrCategory = entityAttrCategory;
    }
    
    @Column(name="element_no", nullable=false)
    public int getElementNo() {
        return this.elementNo;
    }
    
    public void setElementNo(int elementNo) {
        this.elementNo = elementNo;
    }
    
    @Column(name="code")
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    
    @Column(name="value", nullable=false, length=20)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="entityAttrCategoryElement")
    public Set<EntityAttr> getEntityAttrs() {
        return this.entityAttrs;
    }
    
    public void setEntityAttrs(Set<EntityAttr> entityAttrs) {
        this.entityAttrs = entityAttrs;
    }




}


