package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * EntitySpecVer generated by hbm2java
 */
@Entity
@Table(name="entity_spec_ver"
    , uniqueConstraints = @UniqueConstraint(columnNames={"id_entity_spec", "id_spec_rev"}) 
)
public class EntitySpecVer  implements java.io.Serializable {


     private Integer idEntityRev;
     private IteratorContainer iteratorContainer;
     private EntitySpec entitySpecByIdLowerBound;
     private UnitDic unitDic;
     private ModelSpecRev modelSpecRev;
     private EntitySpec entitySpecByIdEntitySpec;
     private EntityRole entityRole;
     private Usr usr;
     private EntitySpec entitySpecByIdUpperBound;
     private EntitySpec entitySpecByIdAssociatedEntity;
     private Date creationDate;
     private int active;
     private String shortDesc;
     private String longDesc;
     private String formula;
     private Set<EntityAttr> entityAttrs = new HashSet<EntityAttr>(0);
     private Set<Term> terms = new HashSet<Term>(0);

    public EntitySpecVer() {
    }

	
    public EntitySpecVer(EntityRole entityRole, int active) {
        this.entityRole = entityRole;
        this.active = active;
    }
    public EntitySpecVer(IteratorContainer iteratorContainer, EntitySpec entitySpecByIdLowerBound, UnitDic unitDic, ModelSpecRev modelSpecRev, EntitySpec entitySpecByIdEntitySpec, EntityRole entityRole, Usr usr, EntitySpec entitySpecByIdUpperBound, EntitySpec entitySpecByIdAssociatedEntity, Date creationDate, int active, String shortDesc, String longDesc, String formula, Set<EntityAttr> entityAttrs, Set<Term> terms) {
       this.iteratorContainer = iteratorContainer;
       this.entitySpecByIdLowerBound = entitySpecByIdLowerBound;
       this.unitDic = unitDic;
       this.modelSpecRev = modelSpecRev;
       this.entitySpecByIdEntitySpec = entitySpecByIdEntitySpec;
       this.entityRole = entityRole;
       this.usr = usr;
       this.entitySpecByIdUpperBound = entitySpecByIdUpperBound;
       this.entitySpecByIdAssociatedEntity = entitySpecByIdAssociatedEntity;
       this.creationDate = creationDate;
       this.active = active;
       this.shortDesc = shortDesc;
       this.longDesc = longDesc;
       this.formula = formula;
       this.entityAttrs = entityAttrs;
       this.terms = terms;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__JPA_ENTITY_SPEC_VER__ID_JPA_ENTITY_SPEC_VER")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_entity_rev", unique=true, nullable=false)
    public Integer getIdEntityRev() {
        return this.idEntityRev;
    }
    
    public void setIdEntityRev(Integer idEntityRev) {
        this.idEntityRev = idEntityRev;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_iter_cont")
    public IteratorContainer getIteratorContainer() {
        return this.iteratorContainer;
    }
    
    public void setIteratorContainer(IteratorContainer iteratorContainer) {
        this.iteratorContainer = iteratorContainer;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_lower_bound")
    public EntitySpec getEntitySpecByIdLowerBound() {
        return this.entitySpecByIdLowerBound;
    }
    
    public void setEntitySpecByIdLowerBound(EntitySpec entitySpecByIdLowerBound) {
        this.entitySpecByIdLowerBound = entitySpecByIdLowerBound;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_unit")
    public UnitDic getUnitDic() {
        return this.unitDic;
    }
    
    public void setUnitDic(UnitDic unitDic) {
        this.unitDic = unitDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_spec_rev")
    public ModelSpecRev getModelSpecRev() {
        return this.modelSpecRev;
    }
    
    public void setModelSpecRev(ModelSpecRev modelSpecRev) {
        this.modelSpecRev = modelSpecRev;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_entity_spec")
    public EntitySpec getEntitySpecByIdEntitySpec() {
        return this.entitySpecByIdEntitySpec;
    }
    
    public void setEntitySpecByIdEntitySpec(EntitySpec entitySpecByIdEntitySpec) {
        this.entitySpecByIdEntitySpec = entitySpecByIdEntitySpec;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_code", nullable=false)
    public EntityRole getEntityRole() {
        return this.entityRole;
    }
    
    public void setEntityRole(EntityRole entityRole) {
        this.entityRole = entityRole;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="created_by")
    public Usr getUsr() {
        return this.usr;
    }
    
    public void setUsr(Usr usr) {
        this.usr = usr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_upper_bound")
    public EntitySpec getEntitySpecByIdUpperBound() {
        return this.entitySpecByIdUpperBound;
    }
    
    public void setEntitySpecByIdUpperBound(EntitySpec entitySpecByIdUpperBound) {
        this.entitySpecByIdUpperBound = entitySpecByIdUpperBound;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_associated_entity")
    public EntitySpec getEntitySpecByIdAssociatedEntity() {
        return this.entitySpecByIdAssociatedEntity;
    }
    
    public void setEntitySpecByIdAssociatedEntity(EntitySpec entitySpecByIdAssociatedEntity) {
        this.entitySpecByIdAssociatedEntity = entitySpecByIdAssociatedEntity;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", length=29)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    
    @Column(name="active", nullable=false)
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }
    
    @Column(name="short_desc", length=20)
    public String getShortDesc() {
        return this.shortDesc;
    }
    
    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
    }
    
    @Column(name="long_desc", length=1000)
    public String getLongDesc() {
        return this.longDesc;
    }
    
    public void setLongDesc(String longDesc) {
        this.longDesc = longDesc;
    }
    
    @Column(name="formula", length=1000)
    public String getFormula() {
        return this.formula;
    }
    
    public void setFormula(String formula) {
        this.formula = formula;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="entitySpecVer")
    public Set<EntityAttr> getEntityAttrs() {
        return this.entityAttrs;
    }
    
    public void setEntityAttrs(Set<EntityAttr> entityAttrs) {
        this.entityAttrs = entityAttrs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="entitySpecVer")
    public Set<Term> getTerms() {
        return this.terms;
    }
    
    public void setTerms(Set<Term> terms) {
        this.terms = terms;
    }




}


