package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FileUploadInfo generated by hbm2java
 */
@Entity
@Table(name="file_upload_info"
)
public class FileUploadInfo  implements java.io.Serializable {


     private Integer idFileUpload;
     private ModelDataUpdate modelDataUpdate;
     private String fileLocation;
     private String fileName;
     private Date fileDate;
     private String fileAuthor;
     private Date dataDate;
     private String dataComment;
     private Set<UploadedSet> uploadedSets = new HashSet<UploadedSet>(0);
     private Set<UploadedEntity> uploadedEntities = new HashSet<UploadedEntity>(0);

    public FileUploadInfo() {
    }

	
    public FileUploadInfo(String fileLocation, String fileName, Date fileDate, Date dataDate) {
        this.fileLocation = fileLocation;
        this.fileName = fileName;
        this.fileDate = fileDate;
        this.dataDate = dataDate;
    }
    public FileUploadInfo(ModelDataUpdate modelDataUpdate, String fileLocation, String fileName, Date fileDate, String fileAuthor, Date dataDate, String dataComment, Set<UploadedSet> uploadedSets, Set<UploadedEntity> uploadedEntities) {
       this.modelDataUpdate = modelDataUpdate;
       this.fileLocation = fileLocation;
       this.fileName = fileName;
       this.fileDate = fileDate;
       this.fileAuthor = fileAuthor;
       this.dataDate = dataDate;
       this.dataComment = dataComment;
       this.uploadedSets = uploadedSets;
       this.uploadedEntities = uploadedEntities;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__JPA_FILE_UPLOAD_INFO__ID_JPA_FILE_UPLOAD_INFO")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_file_upload", unique=true, nullable=false)
    public Integer getIdFileUpload() {
        return this.idFileUpload;
    }
    
    public void setIdFileUpload(Integer idFileUpload) {
        this.idFileUpload = idFileUpload;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_update")
    public ModelDataUpdate getModelDataUpdate() {
        return this.modelDataUpdate;
    }
    
    public void setModelDataUpdate(ModelDataUpdate modelDataUpdate) {
        this.modelDataUpdate = modelDataUpdate;
    }
    
    @Column(name="file_location", nullable=false, length=256)
    public String getFileLocation() {
        return this.fileLocation;
    }
    
    public void setFileLocation(String fileLocation) {
        this.fileLocation = fileLocation;
    }
    
    @Column(name="file_name", nullable=false, length=30)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="file_date", nullable=false, length=29)
    public Date getFileDate() {
        return this.fileDate;
    }
    
    public void setFileDate(Date fileDate) {
        this.fileDate = fileDate;
    }
    
    @Column(name="file_author", length=20)
    public String getFileAuthor() {
        return this.fileAuthor;
    }
    
    public void setFileAuthor(String fileAuthor) {
        this.fileAuthor = fileAuthor;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_date", nullable=false, length=29)
    public Date getDataDate() {
        return this.dataDate;
    }
    
    public void setDataDate(Date dataDate) {
        this.dataDate = dataDate;
    }
    
    @Column(name="data_comment", length=1000)
    public String getDataComment() {
        return this.dataComment;
    }
    
    public void setDataComment(String dataComment) {
        this.dataComment = dataComment;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="fileUploadInfo")
    public Set<UploadedSet> getUploadedSets() {
        return this.uploadedSets;
    }
    
    public void setUploadedSets(Set<UploadedSet> uploadedSets) {
        this.uploadedSets = uploadedSets;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="fileUploadInfo")
    public Set<UploadedEntity> getUploadedEntities() {
        return this.uploadedEntities;
    }
    
    public void setUploadedEntities(Set<UploadedEntity> uploadedEntities) {
        this.uploadedEntities = uploadedEntities;
    }




}


