package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IteratorInContainerId generated by hbm2java
 */
@Embeddable
public class IteratorInContainerId  implements java.io.Serializable {


     private int idIterCont;
     private int idIterAtom;
     private int sequence;

    public IteratorInContainerId() {
    }

    public IteratorInContainerId(int idIterCont, int idIterAtom, int sequence) {
       this.idIterCont = idIterCont;
       this.idIterAtom = idIterAtom;
       this.sequence = sequence;
    }
   

    @Column(name="id_iter_cont", nullable=false)
    public int getIdIterCont() {
        return this.idIterCont;
    }
    
    public void setIdIterCont(int idIterCont) {
        this.idIterCont = idIterCont;
    }

    @Column(name="id_iter_atom", nullable=false)
    public int getIdIterAtom() {
        return this.idIterAtom;
    }
    
    public void setIdIterAtom(int idIterAtom) {
        this.idIterAtom = idIterAtom;
    }

    @Column(name="sequence", nullable=false)
    public int getSequence() {
        return this.sequence;
    }
    
    public void setSequence(int sequence) {
        this.sequence = sequence;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IteratorInContainerId) ) return false;
		 IteratorInContainerId castOther = ( IteratorInContainerId ) other; 
         
		 return (this.getIdIterCont()==castOther.getIdIterCont())
 && (this.getIdIterAtom()==castOther.getIdIterAtom())
 && (this.getSequence()==castOther.getSequence());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdIterCont();
         result = 37 * result + this.getIdIterAtom();
         result = 37 * result + this.getSequence();
         return result;
   }   


}


