package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IteratorAtom generated by hbm2java
 */
@Entity
@Table(name="iterator_atom"
    , uniqueConstraints = @UniqueConstraint(columnNames={"id_model", "id_set_spec", "level", "role", "id_iter_cont"}) 
)
public class IteratorAtom  implements java.io.Serializable {


     private Integer idIterAtom;
     private IteratorContainer iteratorContainer;
     private SetSpec setSpec;
     private Model model;
     private int level;
     private String role;
     private Set<IteratorInContainer> iteratorInContainers = new HashSet<IteratorInContainer>(0);

    public IteratorAtom() {
    }

	
    public IteratorAtom(SetSpec setSpec, int level) {
        this.setSpec = setSpec;
        this.level = level;
    }
    public IteratorAtom(IteratorContainer iteratorContainer, SetSpec setSpec, Model model, int level, String role, Set<IteratorInContainer> iteratorInContainers) {
       this.iteratorContainer = iteratorContainer;
       this.setSpec = setSpec;
       this.model = model;
       this.level = level;
       this.role = role;
       this.iteratorInContainers = iteratorInContainers;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__Jpa_Iterator_Atom__id_Jpa_Iterator_Atom")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_iter_atom", unique=true, nullable=false)
    public Integer getIdIterAtom() {
        return this.idIterAtom;
    }
    
    public void setIdIterAtom(Integer idIterAtom) {
        this.idIterAtom = idIterAtom;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_iter_cont")
    public IteratorContainer getIteratorContainer() {
        return this.iteratorContainer;
    }
    
    public void setIteratorContainer(IteratorContainer iteratorContainer) {
        this.iteratorContainer = iteratorContainer;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_set_spec", nullable=false)
    public SetSpec getSetSpec() {
        return this.setSpec;
    }
    
    public void setSetSpec(SetSpec setSpec) {
        this.setSpec = setSpec;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_model")
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }
    
    @Column(name="level", nullable=false)
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }
    
    @Column(name="role", length=50)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="iteratorAtom")
    public Set<IteratorInContainer> getIteratorInContainers() {
        return this.iteratorInContainers;
    }
    
    public void setIteratorInContainers(Set<IteratorInContainer> iteratorInContainers) {
        this.iteratorInContainers = iteratorInContainers;
    }




}


