package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IteratorInContainer generated by hbm2java
 */
@Entity
@Table(name="iterator_in_container"
)
public class IteratorInContainer  implements java.io.Serializable {


     private IteratorInContainerId id;
     private IteratorContainer iteratorContainer;
     private IteratorAtom iteratorAtom;

    public IteratorInContainer() {
    }

    public IteratorInContainer(IteratorInContainerId id, IteratorContainer iteratorContainer, IteratorAtom iteratorAtom) {
       this.id = id;
       this.iteratorContainer = iteratorContainer;
       this.iteratorAtom = iteratorAtom;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idIterCont", column=@Column(name="id_iter_cont", nullable=false) ), 
        @AttributeOverride(name="idIterAtom", column=@Column(name="id_iter_atom", nullable=false) ), 
        @AttributeOverride(name="sequence", column=@Column(name="sequence", nullable=false) ) } )
    public IteratorInContainerId getId() {
        return this.id;
    }
    
    public void setId(IteratorInContainerId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_iter_cont", nullable=false, insertable=false, updatable=false)
    public IteratorContainer getIteratorContainer() {
        return this.iteratorContainer;
    }
    
    public void setIteratorContainer(IteratorContainer iteratorContainer) {
        this.iteratorContainer = iteratorContainer;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_iter_atom", nullable=false, insertable=false, updatable=false)
    public IteratorAtom getIteratorAtom() {
        return this.iteratorAtom;
    }
    
    public void setIteratorAtom(IteratorAtom iteratorAtom) {
        this.iteratorAtom = iteratorAtom;
    }




}


