package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * IteratorContainer generated by hbm2java
 */
@Entity
@Table(name="iterator_container"
)
public class IteratorContainer  implements java.io.Serializable {


     private Integer idIterCont;
     private Model model;
     private Set<TermEntity> termEntities = new HashSet<TermEntity>(0);
     private Set<IteratorInContainer> iteratorInContainers = new HashSet<IteratorInContainer>(0);
     private Set<Tuple> tuples = new HashSet<Tuple>(0);
     private Set<IteratorAtom> iteratorAtoms = new HashSet<IteratorAtom>(0);
     private Set<SetSpec> setSpecs = new HashSet<SetSpec>(0);
     private Set<EntitySpecVer> entitySpecVers = new HashSet<EntitySpecVer>(0);

    public IteratorContainer() {
    }

    public IteratorContainer(Model model, Set<TermEntity> termEntities, Set<IteratorInContainer> iteratorInContainers, Set<Tuple> tuples, Set<IteratorAtom> iteratorAtoms, Set<SetSpec> setSpecs, Set<EntitySpecVer> entitySpecVers) {
       this.model = model;
       this.termEntities = termEntities;
       this.iteratorInContainers = iteratorInContainers;
       this.tuples = tuples;
       this.iteratorAtoms = iteratorAtoms;
       this.setSpecs = setSpecs;
       this.entitySpecVers = entitySpecVers;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__Jpa_Iterator_Container__id_Jpa_Iterator_Container")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_iter_cont", unique=true, nullable=false)
    public Integer getIdIterCont() {
        return this.idIterCont;
    }
    
    public void setIdIterCont(Integer idIterCont) {
        this.idIterCont = idIterCont;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_model")
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="iteratorContainer")
    public Set<TermEntity> getTermEntities() {
        return this.termEntities;
    }
    
    public void setTermEntities(Set<TermEntity> termEntities) {
        this.termEntities = termEntities;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="iteratorContainer")
    public Set<IteratorInContainer> getIteratorInContainers() {
        return this.iteratorInContainers;
    }
    
    public void setIteratorInContainers(Set<IteratorInContainer> iteratorInContainers) {
        this.iteratorInContainers = iteratorInContainers;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="iteratorContainer")
    public Set<Tuple> getTuples() {
        return this.tuples;
    }
    
    public void setTuples(Set<Tuple> tuples) {
        this.tuples = tuples;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="iteratorContainer")
    public Set<IteratorAtom> getIteratorAtoms() {
        return this.iteratorAtoms;
    }
    
    public void setIteratorAtoms(Set<IteratorAtom> iteratorAtoms) {
        this.iteratorAtoms = iteratorAtoms;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="iteratorContainer")
    public Set<SetSpec> getSetSpecs() {
        return this.setSpecs;
    }
    
    public void setSetSpecs(Set<SetSpec> setSpecs) {
        this.setSpecs = setSpecs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="iteratorContainer")
    public Set<EntitySpecVer> getEntitySpecVers() {
        return this.entitySpecVers;
    }
    
    public void setEntitySpecVers(Set<EntitySpecVer> entitySpecVers) {
        this.entitySpecVers = entitySpecVers;
    }




}


