package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LblLclId generated by hbm2java
 */
@Embeddable
public class LblLclId  implements java.io.Serializable {


     private int idLbl;
     private String idLcl;

    public LblLclId() {
    }

    public LblLclId(int idLbl, String idLcl) {
       this.idLbl = idLbl;
       this.idLcl = idLcl;
    }
   

    @Column(name="id_lbl", nullable=false)
    public int getIdLbl() {
        return this.idLbl;
    }
    
    public void setIdLbl(int idLbl) {
        this.idLbl = idLbl;
    }

    @Column(name="id_lcl", nullable=false, length=5)
    public String getIdLcl() {
        return this.idLcl;
    }
    
    public void setIdLcl(String idLcl) {
        this.idLcl = idLcl;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LblLclId) ) return false;
		 LblLclId castOther = ( LblLclId ) other; 
         
		 return (this.getIdLbl()==castOther.getIdLbl())
 && ( (this.getIdLcl()==castOther.getIdLcl()) || ( this.getIdLcl()!=null && castOther.getIdLcl()!=null && this.getIdLcl().equals(castOther.getIdLcl()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdLbl();
         result = 37 * result + ( getIdLcl() == null ? 0 : this.getIdLcl().hashCode() );
         return result;
   }   


}


