package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LblLg generated by hbm2java
 */
@Entity
@Table(name="lbl_lg"
)
public class LblLg  implements java.io.Serializable {


     private LblLgId id;
     private Srvc srvc;
     private DbSts dbSts;
     private Lbl lbl;
     private Sn sn;

    public LblLg() {
    }

    public LblLg(LblLgId id, Srvc srvc, DbSts dbSts, Lbl lbl, Sn sn) {
       this.id = id;
       this.srvc = srvc;
       this.dbSts = dbSts;
       this.lbl = lbl;
       this.sn = sn;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idLg", column=@Column(name="id_lg", nullable=false) ), 
        @AttributeOverride(name="ts", column=@Column(name="ts", nullable=false, length=29) ) } )
    public LblLgId getId() {
        return this.id;
    }
    
    public void setId(LblLgId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="srvc", nullable=false)
    public Srvc getSrvc() {
        return this.srvc;
    }
    
    public void setSrvc(Srvc srvc) {
        this.srvc = srvc;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_lbl", nullable=false)
    public Lbl getLbl() {
        return this.lbl;
    }
    
    public void setLbl(Lbl lbl) {
        this.lbl = lbl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sn", nullable=false)
    public Sn getSn() {
        return this.sn;
    }
    
    public void setSn(Sn sn) {
        this.sn = sn;
    }




}


