package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LblLclLg generated by hbm2java
 */
@Entity
@Table(name="lbl_lcl_lg"
)
public class LblLclLg  implements java.io.Serializable {


     private LblLclLgId id;
     private Srvc srvc;
     private LblLcl lblLcl;
     private DbSts dbSts;
     private Sn sn;
     private String mnemo;
     private String title;
     private String descr;

    public LblLclLg() {
    }

	
    public LblLclLg(LblLclLgId id, Srvc srvc, LblLcl lblLcl, DbSts dbSts, Sn sn) {
        this.id = id;
        this.srvc = srvc;
        this.lblLcl = lblLcl;
        this.dbSts = dbSts;
        this.sn = sn;
    }
    public LblLclLg(LblLclLgId id, Srvc srvc, LblLcl lblLcl, DbSts dbSts, Sn sn, String mnemo, String title, String descr) {
       this.id = id;
       this.srvc = srvc;
       this.lblLcl = lblLcl;
       this.dbSts = dbSts;
       this.sn = sn;
       this.mnemo = mnemo;
       this.title = title;
       this.descr = descr;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idLg", column=@Column(name="id_lg", nullable=false) ), 
        @AttributeOverride(name="ts", column=@Column(name="ts", nullable=false, length=29) ) } )
    public LblLclLgId getId() {
        return this.id;
    }
    
    public void setId(LblLclLgId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="srvc", nullable=false)
    public Srvc getSrvc() {
        return this.srvc;
    }
    
    public void setSrvc(Srvc srvc) {
        this.srvc = srvc;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="id_lbl", referencedColumnName="id_lbl", nullable=false), 
        @JoinColumn(name="id_lcl", referencedColumnName="id_lcl", nullable=false) } )
    public LblLcl getLblLcl() {
        return this.lblLcl;
    }
    
    public void setLblLcl(LblLcl lblLcl) {
        this.lblLcl = lblLcl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sn", nullable=false)
    public Sn getSn() {
        return this.sn;
    }
    
    public void setSn(Sn sn) {
        this.sn = sn;
    }
    
    @Column(name="mnemo", length=8)
    public String getMnemo() {
        return this.mnemo;
    }
    
    public void setMnemo(String mnemo) {
        this.mnemo = mnemo;
    }
    
    @Column(name="title", length=32)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="descr", length=4000)
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }




}


