package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LblLcl generated by hbm2java
 */
@Entity
@Table(name="lbl_lcl"
)
public class LblLcl  implements java.io.Serializable {


     private LblLclId id;
     private Lcl lcl;
     private DbSts dbSts;
     private Lbl lbl;
     private Sn sn;
     private Boolean isOriginal;
     private String mnemo;
     private String title;
     private String descr;
     private Set<LblLclLg> lblLclLgs = new HashSet<LblLclLg>(0);

    public LblLcl() {
    }

	
    public LblLcl(LblLclId id, Lcl lcl, DbSts dbSts, Lbl lbl, Sn sn) {
        this.id = id;
        this.lcl = lcl;
        this.dbSts = dbSts;
        this.lbl = lbl;
        this.sn = sn;
    }
    public LblLcl(LblLclId id, Lcl lcl, DbSts dbSts, Lbl lbl, Sn sn, Boolean isOriginal, String mnemo, String title, String descr, Set<LblLclLg> lblLclLgs) {
       this.id = id;
       this.lcl = lcl;
       this.dbSts = dbSts;
       this.lbl = lbl;
       this.sn = sn;
       this.isOriginal = isOriginal;
       this.mnemo = mnemo;
       this.title = title;
       this.descr = descr;
       this.lblLclLgs = lblLclLgs;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idLbl", column=@Column(name="id_lbl", nullable=false) ), 
        @AttributeOverride(name="idLcl", column=@Column(name="id_lcl", nullable=false, length=5) ) } )
    public LblLclId getId() {
        return this.id;
    }
    
    public void setId(LblLclId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_lcl", nullable=false, insertable=false, updatable=false)
    public Lcl getLcl() {
        return this.lcl;
    }
    
    public void setLcl(Lcl lcl) {
        this.lcl = lcl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_lbl", nullable=false, insertable=false, updatable=false)
    public Lbl getLbl() {
        return this.lbl;
    }
    
    public void setLbl(Lbl lbl) {
        this.lbl = lbl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sn", nullable=false)
    public Sn getSn() {
        return this.sn;
    }
    
    public void setSn(Sn sn) {
        this.sn = sn;
    }
    
    @Column(name="is_original")
    public Boolean getIsOriginal() {
        return this.isOriginal;
    }
    
    public void setIsOriginal(Boolean isOriginal) {
        this.isOriginal = isOriginal;
    }
    
    @Column(name="mnemo", length=8)
    public String getMnemo() {
        return this.mnemo;
    }
    
    public void setMnemo(String mnemo) {
        this.mnemo = mnemo;
    }
    
    @Column(name="title", length=32)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="descr", length=4000)
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lblLcl")
    public Set<LblLclLg> getLblLclLgs() {
        return this.lblLclLgs;
    }
    
    public void setLblLclLgs(Set<LblLclLg> lblLclLgs) {
        this.lblLclLgs = lblLclLgs;
    }




}


