package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lng generated by hbm2java
 */
@Entity
@Table(name="lng"
)
public class Lng  implements java.io.Serializable {


     private String idLng;
     private DbSts dbSts;
     private Set<Lcl> lcls = new HashSet<Lcl>(0);

    public Lng() {
    }

	
    public Lng(String idLng, DbSts dbSts) {
        this.idLng = idLng;
        this.dbSts = dbSts;
    }
    public Lng(String idLng, DbSts dbSts, Set<Lcl> lcls) {
       this.idLng = idLng;
       this.dbSts = dbSts;
       this.lcls = lcls;
    }
   
     @Id 
    
    @Column(name="id_lng", unique=true, nullable=false, length=2)
    public String getIdLng() {
        return this.idLng;
    }
    
    public void setIdLng(String idLng) {
        this.idLng = idLng;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lng")
    public Set<Lcl> getLcls() {
        return this.lcls;
    }
    
    public void setLcls(Set<Lcl> lcls) {
        this.lcls = lcls;
    }




}


