package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModelType generated by hbm2java
 */
@Entity
@Table(name="model_type"
)
public class ModelType  implements java.io.Serializable {


     private int idModelType;
     private String typeName;
     private Set<Model> models = new HashSet<Model>(0);

    public ModelType() {
    }

	
    public ModelType(int idModelType) {
        this.idModelType = idModelType;
    }
    public ModelType(int idModelType, String typeName, Set<Model> models) {
       this.idModelType = idModelType;
       this.typeName = typeName;
       this.models = models;
    }
   
     @Id 
    
    @Column(name="id_model_type", unique=true, nullable=false)
    public int getIdModelType() {
        return this.idModelType;
    }
    
    public void setIdModelType(int idModelType) {
        this.idModelType = idModelType;
    }
    
    @Column(name="type_name", length=20)
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="modelType")
    public Set<Model> getModels() {
        return this.models;
    }
    
    public void setModels(Set<Model> models) {
        this.models = models;
    }




}


