package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ModelAnalysis generated by hbm2java
 */
@Entity
@Table(name="model_analysis"
)
public class ModelAnalysis  implements java.io.Serializable {


     private Integer idAnalysis;
     private AnalysisType analysisType;
     private Usr usr;
     private ModelInstance modelInstance;
     private String label;
     private Date creationDate;
     private String shortDesc;
     private String longDesc;
     private Set<ComputationalTask> computationalTasks = new HashSet<ComputationalTask>(0);
     private Set<Preference> preferences = new HashSet<Preference>(0);

    public ModelAnalysis() {
    }

	
    public ModelAnalysis(Usr usr, ModelInstance modelInstance, String label, Date creationDate) {
        this.usr = usr;
        this.modelInstance = modelInstance;
        this.label = label;
        this.creationDate = creationDate;
    }
    public ModelAnalysis(AnalysisType analysisType, Usr usr, ModelInstance modelInstance, String label, Date creationDate, String shortDesc, String longDesc, Set<ComputationalTask> computationalTasks, Set<Preference> preferences) {
       this.analysisType = analysisType;
       this.usr = usr;
       this.modelInstance = modelInstance;
       this.label = label;
       this.creationDate = creationDate;
       this.shortDesc = shortDesc;
       this.longDesc = longDesc;
       this.computationalTasks = computationalTasks;
       this.preferences = preferences;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__JPA_MODEL_ANALYSIS__ID_JPA_MODEL_ANALYSIS")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_analysis", unique=true, nullable=false)
    public Integer getIdAnalysis() {
        return this.idAnalysis;
    }
    
    public void setIdAnalysis(Integer idAnalysis) {
        this.idAnalysis = idAnalysis;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_analysis_type")
    public AnalysisType getAnalysisType() {
        return this.analysisType;
    }
    
    public void setAnalysisType(AnalysisType analysisType) {
        this.analysisType = analysisType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="created_by", nullable=false)
    public Usr getUsr() {
        return this.usr;
    }
    
    public void setUsr(Usr usr) {
        this.usr = usr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_instance", nullable=false)
    public ModelInstance getModelInstance() {
        return this.modelInstance;
    }
    
    public void setModelInstance(ModelInstance modelInstance) {
        this.modelInstance = modelInstance;
    }
    
    @Column(name="label", nullable=false, length=12)
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", nullable=false, length=29)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    
    @Column(name="short_desc", length=20)
    public String getShortDesc() {
        return this.shortDesc;
    }
    
    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
    }
    
    @Column(name="long_desc", length=1000)
    public String getLongDesc() {
        return this.longDesc;
    }
    
    public void setLongDesc(String longDesc) {
        this.longDesc = longDesc;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="modelAnalysis")
    public Set<ComputationalTask> getComputationalTasks() {
        return this.computationalTasks;
    }
    
    public void setComputationalTasks(Set<ComputationalTask> computationalTasks) {
        this.computationalTasks = computationalTasks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="modelAnalysis")
    public Set<Preference> getPreferences() {
        return this.preferences;
    }
    
    public void setPreferences(Set<Preference> preferences) {
        this.preferences = preferences;
    }




}


