package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ModelIdentifiers generated by hbm2java
 */
@Entity
@Table(name="model_identifiers"
)
public class ModelIdentifiers  implements java.io.Serializable {


     private int idModel;
     private Model model;
     private Integer nextSpecRev;
     private String default_;
     private Integer nextSubmodelId;
     private Integer nextConstraintLbl;

    public ModelIdentifiers() {
    }

	
    public ModelIdentifiers(int idModel, Model model) {
        this.idModel = idModel;
        this.model = model;
    }
    public ModelIdentifiers(int idModel, Model model, Integer nextSpecRev, String default_, Integer nextSubmodelId, Integer nextConstraintLbl) {
       this.idModel = idModel;
       this.model = model;
       this.nextSpecRev = nextSpecRev;
       this.default_ = default_;
       this.nextSubmodelId = nextSubmodelId;
       this.nextConstraintLbl = nextConstraintLbl;
    }
   
     @Id 
    
    @Column(name="id_model", unique=true, nullable=false)
    public int getIdModel() {
        return this.idModel;
    }
    
    public void setIdModel(int idModel) {
        this.idModel = idModel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_model", unique=true, nullable=false, insertable=false, updatable=false)
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }
    
    @Column(name="next_spec_rev")
    public Integer getNextSpecRev() {
        return this.nextSpecRev;
    }
    
    public void setNextSpecRev(Integer nextSpecRev) {
        this.nextSpecRev = nextSpecRev;
    }
    
    @Column(name="_default_", length=18)
    public String getDefault_() {
        return this.default_;
    }
    
    public void setDefault_(String default_) {
        this.default_ = default_;
    }
    
    @Column(name="next_submodel_id")
    public Integer getNextSubmodelId() {
        return this.nextSubmodelId;
    }
    
    public void setNextSubmodelId(Integer nextSubmodelId) {
        this.nextSubmodelId = nextSubmodelId;
    }
    
    @Column(name="next_constraint_lbl")
    public Integer getNextConstraintLbl() {
        return this.nextConstraintLbl;
    }
    
    public void setNextConstraintLbl(Integer nextConstraintLbl) {
        this.nextConstraintLbl = nextConstraintLbl;
    }




}


