package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ModelSpecRev generated by hbm2java
 */
@Entity
@Table(name="model_spec_rev"
    , uniqueConstraints = @UniqueConstraint(columnNames={"id_model", "rev_no"}) 
)
public class ModelSpecRev  implements java.io.Serializable {


     private Integer idSpecRev;
     private Sn snByLckSts;
     private Usr usrByModifiedBy;
     private DbSts dbSts;
     private Usr usrByCommitedBy;
     private Usr usrByCreatedBy;
     private ModelSpecRev modelSpecRev;
     private Model model;
     private SpecState specState;
     private Sn snBySn;
     private Integer revNo;
     private Date creationDate;
     private Date modificationDate;
     private Date commitDate;
     private String shortDesc;
     private String longDesc;
     private Set<Comments> commentses = new HashSet<Comments>(0);
     private Set<ModelInstance> modelInstances = new HashSet<ModelInstance>(0);
     private Set<SetSpecVer> setSpecVers = new HashSet<SetSpecVer>(0);
     private Set<EntitySpecVer> entitySpecVers = new HashSet<EntitySpecVer>(0);
     private Set<ModelSpecRev> modelSpecRevs = new HashSet<ModelSpecRev>(0);

    public ModelSpecRev() {
    }

	
    public ModelSpecRev(Usr usrByCreatedBy, Date creationDate) {
        this.usrByCreatedBy = usrByCreatedBy;
        this.creationDate = creationDate;
    }
    public ModelSpecRev(Sn snByLckSts, Usr usrByModifiedBy, DbSts dbSts, Usr usrByCommitedBy, Usr usrByCreatedBy, ModelSpecRev modelSpecRev, Model model, SpecState specState, Sn snBySn, Integer revNo, Date creationDate, Date modificationDate, Date commitDate, String shortDesc, String longDesc, Set<Comments> commentses, Set<ModelInstance> modelInstances, Set<SetSpecVer> setSpecVers, Set<EntitySpecVer> entitySpecVers, Set<ModelSpecRev> modelSpecRevs) {
       this.snByLckSts = snByLckSts;
       this.usrByModifiedBy = usrByModifiedBy;
       this.dbSts = dbSts;
       this.usrByCommitedBy = usrByCommitedBy;
       this.usrByCreatedBy = usrByCreatedBy;
       this.modelSpecRev = modelSpecRev;
       this.model = model;
       this.specState = specState;
       this.snBySn = snBySn;
       this.revNo = revNo;
       this.creationDate = creationDate;
       this.modificationDate = modificationDate;
       this.commitDate = commitDate;
       this.shortDesc = shortDesc;
       this.longDesc = longDesc;
       this.commentses = commentses;
       this.modelInstances = modelInstances;
       this.setSpecVers = setSpecVers;
       this.entitySpecVers = entitySpecVers;
       this.modelSpecRevs = modelSpecRevs;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__JPA_MODEL_SPEC_REV__ID_JPA_MODEL_SPEC_REV")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_spec_rev", unique=true, nullable=false)
    public Integer getIdSpecRev() {
        return this.idSpecRev;
    }
    
    public void setIdSpecRev(Integer idSpecRev) {
        this.idSpecRev = idSpecRev;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lck_sts")
    public Sn getSnByLckSts() {
        return this.snByLckSts;
    }
    
    public void setSnByLckSts(Sn snByLckSts) {
        this.snByLckSts = snByLckSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="modified_by")
    public Usr getUsrByModifiedBy() {
        return this.usrByModifiedBy;
    }
    
    public void setUsrByModifiedBy(Usr usrByModifiedBy) {
        this.usrByModifiedBy = usrByModifiedBy;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts")
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="commited_by")
    public Usr getUsrByCommitedBy() {
        return this.usrByCommitedBy;
    }
    
    public void setUsrByCommitedBy(Usr usrByCommitedBy) {
        this.usrByCommitedBy = usrByCommitedBy;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="created_by", nullable=false)
    public Usr getUsrByCreatedBy() {
        return this.usrByCreatedBy;
    }
    
    public void setUsrByCreatedBy(Usr usrByCreatedBy) {
        this.usrByCreatedBy = usrByCreatedBy;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent_id_spec_rev")
    public ModelSpecRev getModelSpecRev() {
        return this.modelSpecRev;
    }
    
    public void setModelSpecRev(ModelSpecRev modelSpecRev) {
        this.modelSpecRev = modelSpecRev;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_model")
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_spec_state")
    public SpecState getSpecState() {
        return this.specState;
    }
    
    public void setSpecState(SpecState specState) {
        this.specState = specState;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sn")
    public Sn getSnBySn() {
        return this.snBySn;
    }
    
    public void setSnBySn(Sn snBySn) {
        this.snBySn = snBySn;
    }
    
    @Column(name="rev_no")
    public Integer getRevNo() {
        return this.revNo;
    }
    
    public void setRevNo(Integer revNo) {
        this.revNo = revNo;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", nullable=false, length=29)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modification_date", length=29)
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="commit_date", length=29)
    public Date getCommitDate() {
        return this.commitDate;
    }
    
    public void setCommitDate(Date commitDate) {
        this.commitDate = commitDate;
    }
    
    @Column(name="short_desc", length=20)
    public String getShortDesc() {
        return this.shortDesc;
    }
    
    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
    }
    
    @Column(name="long_desc", length=1000)
    public String getLongDesc() {
        return this.longDesc;
    }
    
    public void setLongDesc(String longDesc) {
        this.longDesc = longDesc;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="modelSpecRev")
    public Set<Comments> getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="modelSpecRev")
    public Set<ModelInstance> getModelInstances() {
        return this.modelInstances;
    }
    
    public void setModelInstances(Set<ModelInstance> modelInstances) {
        this.modelInstances = modelInstances;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="modelSpecRev")
    public Set<SetSpecVer> getSetSpecVers() {
        return this.setSpecVers;
    }
    
    public void setSetSpecVers(Set<SetSpecVer> setSpecVers) {
        this.setSpecVers = setSpecVers;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="modelSpecRev")
    public Set<EntitySpecVer> getEntitySpecVers() {
        return this.entitySpecVers;
    }
    
    public void setEntitySpecVers(Set<EntitySpecVer> entitySpecVers) {
        this.entitySpecVers = entitySpecVers;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="modelSpecRev")
    public Set<ModelSpecRev> getModelSpecRevs() {
        return this.modelSpecRevs;
    }
    
    public void setModelSpecRevs(Set<ModelSpecRev> modelSpecRevs) {
        this.modelSpecRevs = modelSpecRevs;
    }




}


