package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ModelInstance generated by hbm2java
 */
@Entity
@Table(name="model_instance"
)
public class ModelInstance  implements java.io.Serializable {


     private Integer idInstance;
     private ModelSpecRev modelSpecRev;
     private Usr usr;
     private ModelDataUpdate modelDataUpdate;
     private InstanceState instanceState;
     private Model model;
     private String label;
     private Date creationDate;
     private String shortDesc;
     private String longDesc;
     private Set<ModelAnalysis> modelAnalysises = new HashSet<ModelAnalysis>(0);

    public ModelInstance() {
    }

	
    public ModelInstance(Usr usr, InstanceState instanceState) {
        this.usr = usr;
        this.instanceState = instanceState;
    }
    public ModelInstance(ModelSpecRev modelSpecRev, Usr usr, ModelDataUpdate modelDataUpdate, InstanceState instanceState, Model model, String label, Date creationDate, String shortDesc, String longDesc, Set<ModelAnalysis> modelAnalysises) {
       this.modelSpecRev = modelSpecRev;
       this.usr = usr;
       this.modelDataUpdate = modelDataUpdate;
       this.instanceState = instanceState;
       this.model = model;
       this.label = label;
       this.creationDate = creationDate;
       this.shortDesc = shortDesc;
       this.longDesc = longDesc;
       this.modelAnalysises = modelAnalysises;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__JPA_MODEL_INSTANCE__ID_JPA_MODEL_INSTANCE")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_instance", unique=true, nullable=false)
    public Integer getIdInstance() {
        return this.idInstance;
    }
    
    public void setIdInstance(Integer idInstance) {
        this.idInstance = idInstance;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_spec_rev")
    public ModelSpecRev getModelSpecRev() {
        return this.modelSpecRev;
    }
    
    public void setModelSpecRev(ModelSpecRev modelSpecRev) {
        this.modelSpecRev = modelSpecRev;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="created_by", nullable=false)
    public Usr getUsr() {
        return this.usr;
    }
    
    public void setUsr(Usr usr) {
        this.usr = usr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_update")
    public ModelDataUpdate getModelDataUpdate() {
        return this.modelDataUpdate;
    }
    
    public void setModelDataUpdate(ModelDataUpdate modelDataUpdate) {
        this.modelDataUpdate = modelDataUpdate;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_state", nullable=false)
    public InstanceState getInstanceState() {
        return this.instanceState;
    }
    
    public void setInstanceState(InstanceState instanceState) {
        this.instanceState = instanceState;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_model")
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }
    
    @Column(name="label", length=20)
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", length=29)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    
    @Column(name="short_desc", length=20)
    public String getShortDesc() {
        return this.shortDesc;
    }
    
    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
    }
    
    @Column(name="long_desc", length=1000)
    public String getLongDesc() {
        return this.longDesc;
    }
    
    public void setLongDesc(String longDesc) {
        this.longDesc = longDesc;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="modelInstance")
    public Set<ModelAnalysis> getModelAnalysises() {
        return this.modelAnalysises;
    }
    
    public void setModelAnalysises(Set<ModelAnalysis> modelAnalysises) {
        this.modelAnalysises = modelAnalysises;
    }




}


