package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Msg generated by hbm2java
 */
@Entity
@Table(name="msg"
)
public class Msg  implements java.io.Serializable {


     private String idMsg;
     private Sn snByLckSts;
     private DbSts dbSts;
     private Sn snBySn;
     private Set<DbSts> dbStses = new HashSet<DbSts>(0);
     private Set<MsgLg> msgLgs = new HashSet<MsgLg>(0);
     private Set<EdtSts> edtStses = new HashSet<EdtSts>(0);
     private Set<MsgLcl> msgLcls = new HashSet<MsgLcl>(0);

    public Msg() {
    }

	
    public Msg(String idMsg, DbSts dbSts, Sn snBySn) {
        this.idMsg = idMsg;
        this.dbSts = dbSts;
        this.snBySn = snBySn;
    }
    public Msg(String idMsg, Sn snByLckSts, DbSts dbSts, Sn snBySn, Set<DbSts> dbStses, Set<MsgLg> msgLgs, Set<EdtSts> edtStses, Set<MsgLcl> msgLcls) {
       this.idMsg = idMsg;
       this.snByLckSts = snByLckSts;
       this.dbSts = dbSts;
       this.snBySn = snBySn;
       this.dbStses = dbStses;
       this.msgLgs = msgLgs;
       this.edtStses = edtStses;
       this.msgLcls = msgLcls;
    }
   
     @Id 
    
    @Column(name="id_msg", unique=true, nullable=false, length=64)
    public String getIdMsg() {
        return this.idMsg;
    }
    
    public void setIdMsg(String idMsg) {
        this.idMsg = idMsg;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lck_sts")
    public Sn getSnByLckSts() {
        return this.snByLckSts;
    }
    
    public void setSnByLckSts(Sn snByLckSts) {
        this.snByLckSts = snByLckSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sn", nullable=false)
    public Sn getSnBySn() {
        return this.snBySn;
    }
    
    public void setSnBySn(Sn snBySn) {
        this.snBySn = snBySn;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="msg")
    public Set<DbSts> getDbStses() {
        return this.dbStses;
    }
    
    public void setDbStses(Set<DbSts> dbStses) {
        this.dbStses = dbStses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="msg")
    public Set<MsgLg> getMsgLgs() {
        return this.msgLgs;
    }
    
    public void setMsgLgs(Set<MsgLg> msgLgs) {
        this.msgLgs = msgLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="msg")
    public Set<EdtSts> getEdtStses() {
        return this.edtStses;
    }
    
    public void setEdtStses(Set<EdtSts> edtStses) {
        this.edtStses = edtStses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="msg")
    public Set<MsgLcl> getMsgLcls() {
        return this.msgLcls;
    }
    
    public void setMsgLcls(Set<MsgLcl> msgLcls) {
        this.msgLcls = msgLcls;
    }




}


