package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MsgLclLg generated by hbm2java
 */
@Entity
@Table(name="msg_lcl_lg"
)
public class MsgLclLg  implements java.io.Serializable {


     private MsgLclLgId id;
     private Srvc srvc;
     private DbSts dbSts;
     private MsgLcl msgLcl;
     private Sn sn;
     private String message;

    public MsgLclLg() {
    }

    public MsgLclLg(MsgLclLgId id, Srvc srvc, DbSts dbSts, MsgLcl msgLcl, Sn sn, String message) {
       this.id = id;
       this.srvc = srvc;
       this.dbSts = dbSts;
       this.msgLcl = msgLcl;
       this.sn = sn;
       this.message = message;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idLg", column=@Column(name="id_lg", nullable=false) ), 
        @AttributeOverride(name="ts", column=@Column(name="ts", nullable=false, length=29) ) } )
    public MsgLclLgId getId() {
        return this.id;
    }
    
    public void setId(MsgLclLgId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="srvc", nullable=false)
    public Srvc getSrvc() {
        return this.srvc;
    }
    
    public void setSrvc(Srvc srvc) {
        this.srvc = srvc;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="id_msg", referencedColumnName="id_msg", nullable=false), 
        @JoinColumn(name="id_lcl", referencedColumnName="id_lcl", nullable=false) } )
    public MsgLcl getMsgLcl() {
        return this.msgLcl;
    }
    
    public void setMsgLcl(MsgLcl msgLcl) {
        this.msgLcl = msgLcl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sn", nullable=false)
    public Sn getSn() {
        return this.sn;
    }
    
    public void setSn(Sn sn) {
        this.sn = sn;
    }
    
    @Column(name="message", nullable=false, length=1024)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


