package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MsgLcl generated by hbm2java
 */
@Entity
@Table(name="msg_lcl"
)
public class MsgLcl  implements java.io.Serializable {


     private MsgLclId id;
     private Msg msg;
     private Lcl lcl;
     private DbSts dbSts;
     private Sn sn;
     private Boolean isOriginal;
     private String message;
     private Set<MsgLclLg> msgLclLgs = new HashSet<MsgLclLg>(0);

    public MsgLcl() {
    }

	
    public MsgLcl(MsgLclId id, Msg msg, Lcl lcl, DbSts dbSts, Sn sn, String message) {
        this.id = id;
        this.msg = msg;
        this.lcl = lcl;
        this.dbSts = dbSts;
        this.sn = sn;
        this.message = message;
    }
    public MsgLcl(MsgLclId id, Msg msg, Lcl lcl, DbSts dbSts, Sn sn, Boolean isOriginal, String message, Set<MsgLclLg> msgLclLgs) {
       this.id = id;
       this.msg = msg;
       this.lcl = lcl;
       this.dbSts = dbSts;
       this.sn = sn;
       this.isOriginal = isOriginal;
       this.message = message;
       this.msgLclLgs = msgLclLgs;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idMsg", column=@Column(name="id_msg", nullable=false, length=64) ), 
        @AttributeOverride(name="idLcl", column=@Column(name="id_lcl", nullable=false, length=5) ) } )
    public MsgLclId getId() {
        return this.id;
    }
    
    public void setId(MsgLclId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_msg", nullable=false, insertable=false, updatable=false)
    public Msg getMsg() {
        return this.msg;
    }
    
    public void setMsg(Msg msg) {
        this.msg = msg;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_lcl", nullable=false, insertable=false, updatable=false)
    public Lcl getLcl() {
        return this.lcl;
    }
    
    public void setLcl(Lcl lcl) {
        this.lcl = lcl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sn", nullable=false)
    public Sn getSn() {
        return this.sn;
    }
    
    public void setSn(Sn sn) {
        this.sn = sn;
    }
    
    @Column(name="is_original")
    public Boolean getIsOriginal() {
        return this.isOriginal;
    }
    
    public void setIsOriginal(Boolean isOriginal) {
        this.isOriginal = isOriginal;
    }
    
    @Column(name="message", nullable=false, length=1024)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="msgLcl")
    public Set<MsgLclLg> getMsgLclLgs() {
        return this.msgLclLgs;
    }
    
    public void setMsgLclLgs(Set<MsgLclLg> msgLclLgs) {
        this.msgLclLgs = msgLclLgs;
    }




}


