package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 18, 2011 2:44:24 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ObjTpSrvcRlLg generated by hbm2java
 */
@Entity
@Table(name="obj_tp_srvc_rl_lg"
)
public class ObjTpSrvcRlLg  implements java.io.Serializable {


     private ObjTpSrvcRlLgId id;
     private DbSts dbSts;
     private ObjTpSrvcRl objTpSrvcRl;
     private short srvc;
     private String sn;

    public ObjTpSrvcRlLg() {
    }

    public ObjTpSrvcRlLg(ObjTpSrvcRlLgId id, DbSts dbSts, ObjTpSrvcRl objTpSrvcRl, short srvc, String sn) {
       this.id = id;
       this.dbSts = dbSts;
       this.objTpSrvcRl = objTpSrvcRl;
       this.srvc = srvc;
       this.sn = sn;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idLg", column=@Column(name="id_lg", nullable=false) ), 
        @AttributeOverride(name="ts", column=@Column(name="ts", nullable=false, length=29) ) } )
    public ObjTpSrvcRlLgId getId() {
        return this.id;
    }
    
    public void setId(ObjTpSrvcRlLgId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="id_obj_tp", referencedColumnName="id_obj_tp", nullable=false), 
        @JoinColumn(name="id_srvc", referencedColumnName="id_srvc", nullable=false), 
        @JoinColumn(name="id_rl", referencedColumnName="id_rl", nullable=false) } )
    public ObjTpSrvcRl getObjTpSrvcRl() {
        return this.objTpSrvcRl;
    }
    
    public void setObjTpSrvcRl(ObjTpSrvcRl objTpSrvcRl) {
        this.objTpSrvcRl = objTpSrvcRl;
    }
    
    @Column(name="srvc", nullable=false)
    public short getSrvc() {
        return this.srvc;
    }
    
    public void setSrvc(short srvc) {
        this.srvc = srvc;
    }
    
    @Column(name="sn", nullable=false, length=256)
    public String getSn() {
        return this.sn;
    }
    
    public void setSn(String sn) {
        this.sn = sn;
    }




}


