package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 18, 2011 2:44:24 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ObjTpSrvcRl generated by hbm2java
 */
@Entity
@Table(name="obj_tp_srvc_rl"
)
public class ObjTpSrvcRl  implements java.io.Serializable {


     private ObjTpSrvcRlId id;
     private ObjTpSrvc objTpSrvc;
     private DbSts dbSts;
     private String sn;
     private Set<ObjTpSrvcRlLg> objTpSrvcRlLgs = new HashSet<ObjTpSrvcRlLg>(0);

    public ObjTpSrvcRl() {
    }

	
    public ObjTpSrvcRl(ObjTpSrvcRlId id, ObjTpSrvc objTpSrvc, DbSts dbSts, String sn) {
        this.id = id;
        this.objTpSrvc = objTpSrvc;
        this.dbSts = dbSts;
        this.sn = sn;
    }
    public ObjTpSrvcRl(ObjTpSrvcRlId id, ObjTpSrvc objTpSrvc, DbSts dbSts, String sn, Set<ObjTpSrvcRlLg> objTpSrvcRlLgs) {
       this.id = id;
       this.objTpSrvc = objTpSrvc;
       this.dbSts = dbSts;
       this.sn = sn;
       this.objTpSrvcRlLgs = objTpSrvcRlLgs;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idObjTp", column=@Column(name="id_obj_tp", nullable=false) ), 
        @AttributeOverride(name="idSrvc", column=@Column(name="id_srvc", nullable=false) ), 
        @AttributeOverride(name="idRl", column=@Column(name="id_rl", nullable=false) ) } )
    public ObjTpSrvcRlId getId() {
        return this.id;
    }
    
    public void setId(ObjTpSrvcRlId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="id_obj_tp", referencedColumnName="id_obj_tp", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="id_srvc", referencedColumnName="id_srvc", nullable=false, insertable=false, updatable=false) } )
    public ObjTpSrvc getObjTpSrvc() {
        return this.objTpSrvc;
    }
    
    public void setObjTpSrvc(ObjTpSrvc objTpSrvc) {
        this.objTpSrvc = objTpSrvc;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
    
    @Column(name="sn", nullable=false, length=256)
    public String getSn() {
        return this.sn;
    }
    
    public void setSn(String sn) {
        this.sn = sn;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="objTpSrvcRl")
    public Set<ObjTpSrvcRlLg> getObjTpSrvcRlLgs() {
        return this.objTpSrvcRlLgs;
    }
    
    public void setObjTpSrvcRlLgs(Set<ObjTpSrvcRlLg> objTpSrvcRlLgs) {
        this.objTpSrvcRlLgs = objTpSrvcRlLgs;
    }




}


