package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 18, 2011 2:44:24 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObjTpSrvcId generated by hbm2java
 */
@Embeddable
public class ObjTpSrvcId  implements java.io.Serializable {


     private short idObjTp;
     private short idSrvc;

    public ObjTpSrvcId() {
    }

    public ObjTpSrvcId(short idObjTp, short idSrvc) {
       this.idObjTp = idObjTp;
       this.idSrvc = idSrvc;
    }
   

    @Column(name="id_obj_tp", nullable=false)
    public short getIdObjTp() {
        return this.idObjTp;
    }
    
    public void setIdObjTp(short idObjTp) {
        this.idObjTp = idObjTp;
    }

    @Column(name="id_srvc", nullable=false)
    public short getIdSrvc() {
        return this.idSrvc;
    }
    
    public void setIdSrvc(short idSrvc) {
        this.idSrvc = idSrvc;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ObjTpSrvcId) ) return false;
		 ObjTpSrvcId castOther = ( ObjTpSrvcId ) other; 
         
		 return (this.getIdObjTp()==castOther.getIdObjTp())
 && (this.getIdSrvc()==castOther.getIdSrvc());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdObjTp();
         result = 37 * result + this.getIdSrvc();
         return result;
   }   


}


