package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 18, 2011 2:44:24 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ObjTp generated by hbm2java
 */
@Entity
@Table(name="obj_tp"
)
public class ObjTp  implements java.io.Serializable {


     private short idObjTp;
     private String clsNm;
     private Set<ObjTpSrvc> objTpSrvcs = new HashSet<ObjTpSrvc>(0);

    public ObjTp() {
    }

	
    public ObjTp(short idObjTp) {
        this.idObjTp = idObjTp;
    }
    public ObjTp(short idObjTp, String clsNm, Set<ObjTpSrvc> objTpSrvcs) {
       this.idObjTp = idObjTp;
       this.clsNm = clsNm;
       this.objTpSrvcs = objTpSrvcs;
    }
   
     @Id 
    
    @Column(name="id_obj_tp", unique=true, nullable=false)
    public short getIdObjTp() {
        return this.idObjTp;
    }
    
    public void setIdObjTp(short idObjTp) {
        this.idObjTp = idObjTp;
    }
    
    @Column(name="cls_nm", length=1024)
    public String getClsNm() {
        return this.clsNm;
    }
    
    public void setClsNm(String clsNm) {
        this.clsNm = clsNm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="objTp")
    public Set<ObjTpSrvc> getObjTpSrvcs() {
        return this.objTpSrvcs;
    }
    
    public void setObjTpSrvcs(Set<ObjTpSrvc> objTpSrvcs) {
        this.objTpSrvcs = objTpSrvcs;
    }




}


