package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 18, 2011 2:44:24 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObjTpSrvcRlId generated by hbm2java
 */
@Embeddable
public class ObjTpSrvcRlId  implements java.io.Serializable {


     private short idObjTp;
     private short idSrvc;
     private short idRl;

    public ObjTpSrvcRlId() {
    }

    public ObjTpSrvcRlId(short idObjTp, short idSrvc, short idRl) {
       this.idObjTp = idObjTp;
       this.idSrvc = idSrvc;
       this.idRl = idRl;
    }
   

    @Column(name="id_obj_tp", nullable=false)
    public short getIdObjTp() {
        return this.idObjTp;
    }
    
    public void setIdObjTp(short idObjTp) {
        this.idObjTp = idObjTp;
    }

    @Column(name="id_srvc", nullable=false)
    public short getIdSrvc() {
        return this.idSrvc;
    }
    
    public void setIdSrvc(short idSrvc) {
        this.idSrvc = idSrvc;
    }

    @Column(name="id_rl", nullable=false)
    public short getIdRl() {
        return this.idRl;
    }
    
    public void setIdRl(short idRl) {
        this.idRl = idRl;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ObjTpSrvcRlId) ) return false;
		 ObjTpSrvcRlId castOther = ( ObjTpSrvcRlId ) other; 
         
		 return (this.getIdObjTp()==castOther.getIdObjTp())
 && (this.getIdSrvc()==castOther.getIdSrvc())
 && (this.getIdRl()==castOther.getIdRl());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdObjTp();
         result = 37 * result + this.getIdSrvc();
         result = 37 * result + this.getIdRl();
         return result;
   }   


}


