package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Preference generated by hbm2java
 */
@Entity
@Table(name="preference"
)
public class Preference  implements java.io.Serializable {


     private String idPreference;
     private ModelAnalysis modelAnalysis;
     private EntitySpec entitySpec;
     private PreferenceType preferenceType;
     private Double prefValue;

    public Preference() {
    }

	
    public Preference(ModelAnalysis modelAnalysis) {
        this.modelAnalysis = modelAnalysis;
    }
    public Preference(ModelAnalysis modelAnalysis, EntitySpec entitySpec, PreferenceType preferenceType, Double prefValue) {
       this.modelAnalysis = modelAnalysis;
       this.entitySpec = entitySpec;
       this.preferenceType = preferenceType;
       this.prefValue = prefValue;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__JPA_PREFERENCE__ID_JPA_PREFERENCE")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_preference", unique=true, nullable=false, length=18)
    public String getIdPreference() {
        return this.idPreference;
    }
    
    public void setIdPreference(String idPreference) {
        this.idPreference = idPreference;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_analysis", nullable=false)
    public ModelAnalysis getModelAnalysis() {
        return this.modelAnalysis;
    }
    
    public void setModelAnalysis(ModelAnalysis modelAnalysis) {
        this.modelAnalysis = modelAnalysis;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_entity_spec")
    public EntitySpec getEntitySpec() {
        return this.entitySpec;
    }
    
    public void setEntitySpec(EntitySpec entitySpec) {
        this.entitySpec = entitySpec;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pref_type")
    public PreferenceType getPreferenceType() {
        return this.preferenceType;
    }
    
    public void setPreferenceType(PreferenceType preferenceType) {
        this.preferenceType = preferenceType;
    }
    
    @Column(name="pref_value", precision=17, scale=17)
    public Double getPrefValue() {
        return this.prefValue;
    }
    
    public void setPrefValue(Double prefValue) {
        this.prefValue = prefValue;
    }




}


