package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ResultsStorageType generated by hbm2java
 */
@Entity
@Table(name="results_storage_type"
)
public class ResultsStorageType  implements java.io.Serializable {


     private int idResultsStorage;
     private String resultsStorageName;
     private Set<ComputationalTask> computationalTasks = new HashSet<ComputationalTask>(0);

    public ResultsStorageType() {
    }

	
    public ResultsStorageType(int idResultsStorage, String resultsStorageName) {
        this.idResultsStorage = idResultsStorage;
        this.resultsStorageName = resultsStorageName;
    }
    public ResultsStorageType(int idResultsStorage, String resultsStorageName, Set<ComputationalTask> computationalTasks) {
       this.idResultsStorage = idResultsStorage;
       this.resultsStorageName = resultsStorageName;
       this.computationalTasks = computationalTasks;
    }
   
     @Id 
    
    @Column(name="id_results_storage", unique=true, nullable=false)
    public int getIdResultsStorage() {
        return this.idResultsStorage;
    }
    
    public void setIdResultsStorage(int idResultsStorage) {
        this.idResultsStorage = idResultsStorage;
    }
    
    @Column(name="results_storage_name", nullable=false, length=18)
    public String getResultsStorageName() {
        return this.resultsStorageName;
    }
    
    public void setResultsStorageName(String resultsStorageName) {
        this.resultsStorageName = resultsStorageName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="resultsStorageType")
    public Set<ComputationalTask> getComputationalTasks() {
        return this.computationalTasks;
    }
    
    public void setComputationalTasks(Set<ComputationalTask> computationalTasks) {
        this.computationalTasks = computationalTasks;
    }




}


