package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SetAttrCategoryElement generated by hbm2java
 */
@Entity
@Table(name="set_attr_category_element"
)
public class SetAttrCategoryElement  implements java.io.Serializable {


     private SetAttrCategoryElementId id;
     private SetAttrCategory setAttrCategory;
     private Integer code;
     private String value;
     private Set<SetAttr> setAttrs = new HashSet<SetAttr>(0);

    public SetAttrCategoryElement() {
    }

	
    public SetAttrCategoryElement(SetAttrCategoryElementId id, SetAttrCategory setAttrCategory, String value) {
        this.id = id;
        this.setAttrCategory = setAttrCategory;
        this.value = value;
    }
    public SetAttrCategoryElement(SetAttrCategoryElementId id, SetAttrCategory setAttrCategory, Integer code, String value, Set<SetAttr> setAttrs) {
       this.id = id;
       this.setAttrCategory = setAttrCategory;
       this.code = code;
       this.value = value;
       this.setAttrs = setAttrs;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idCategory", column=@Column(name="id_category", nullable=false) ), 
        @AttributeOverride(name="elementNo", column=@Column(name="element_no", nullable=false) ) } )
    public SetAttrCategoryElementId getId() {
        return this.id;
    }
    
    public void setId(SetAttrCategoryElementId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_category", nullable=false, insertable=false, updatable=false)
    public SetAttrCategory getSetAttrCategory() {
        return this.setAttrCategory;
    }
    
    public void setSetAttrCategory(SetAttrCategory setAttrCategory) {
        this.setAttrCategory = setAttrCategory;
    }
    
    @Column(name="code")
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    
    @Column(name="value", nullable=false, length=30)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="setAttrCategoryElement")
    public Set<SetAttr> getSetAttrs() {
        return this.setAttrs;
    }
    
    public void setSetAttrs(Set<SetAttr> setAttrs) {
        this.setAttrs = setAttrs;
    }




}


