package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SetAttrCategory generated by hbm2java
 */
@Entity
@Table(name="set_attr_category"
)
public class SetAttrCategory  implements java.io.Serializable {


     private Integer idCategory;
     private String categoryName;
     private Integer catOrder;
     private Set<SetAttrCategoryElement> setAttrCategoryElements = new HashSet<SetAttrCategoryElement>(0);
     private Set<SetAttr> setAttrs = new HashSet<SetAttr>(0);

    public SetAttrCategory() {
    }

	
    public SetAttrCategory(String categoryName) {
        this.categoryName = categoryName;
    }
    public SetAttrCategory(String categoryName, Integer catOrder, Set<SetAttrCategoryElement> setAttrCategoryElements, Set<SetAttr> setAttrs) {
       this.categoryName = categoryName;
       this.catOrder = catOrder;
       this.setAttrCategoryElements = setAttrCategoryElements;
       this.setAttrs = setAttrs;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__JPA_SET_ATTR_CATEGORY__ID_JPA_SET_ATTR_CATEGORY")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_category", unique=true, nullable=false)
    public Integer getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(Integer idCategory) {
        this.idCategory = idCategory;
    }
    
    @Column(name="category_name", nullable=false, length=30)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    
    @Column(name="cat_order")
    public Integer getCatOrder() {
        return this.catOrder;
    }
    
    public void setCatOrder(Integer catOrder) {
        this.catOrder = catOrder;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="setAttrCategory")
    public Set<SetAttrCategoryElement> getSetAttrCategoryElements() {
        return this.setAttrCategoryElements;
    }
    
    public void setSetAttrCategoryElements(Set<SetAttrCategoryElement> setAttrCategoryElements) {
        this.setAttrCategoryElements = setAttrCategoryElements;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="setAttrCategory")
    public Set<SetAttr> getSetAttrs() {
        return this.setAttrs;
    }
    
    public void setSetAttrs(Set<SetAttr> setAttrs) {
        this.setAttrs = setAttrs;
    }




}


