package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SetAttr generated by hbm2java
 */
@Entity
@Table(name="set_attr"
    , uniqueConstraints = @UniqueConstraint(columnNames={"id_set_rev", "id_category"}) 
)
public class SetAttr  implements java.io.Serializable {


     private Integer idSetAttr;
     private SetAttrCategoryElement setAttrCategoryElement;
     private SetSpecVer setSpecVer;
     private SetAttrCategory setAttrCategory;

    public SetAttr() {
    }

	
    public SetAttr(SetAttrCategoryElement setAttrCategoryElement, SetSpecVer setSpecVer) {
        this.setAttrCategoryElement = setAttrCategoryElement;
        this.setSpecVer = setSpecVer;
    }
    public SetAttr(SetAttrCategoryElement setAttrCategoryElement, SetSpecVer setSpecVer, SetAttrCategory setAttrCategory) {
       this.setAttrCategoryElement = setAttrCategoryElement;
       this.setSpecVer = setSpecVer;
       this.setAttrCategory = setAttrCategory;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__JPA_SET_ATTR__ID_JPA_SET_ATTR")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_set_attr", unique=true, nullable=false)
    public Integer getIdSetAttr() {
        return this.idSetAttr;
    }
    
    public void setIdSetAttr(Integer idSetAttr) {
        this.idSetAttr = idSetAttr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="id_category", referencedColumnName="id_category"), 
        @JoinColumn(name="element_no", referencedColumnName="element_no") } )
    public SetAttrCategoryElement getSetAttrCategoryElement() {
        return this.setAttrCategoryElement;
    }
    
    public void setSetAttrCategoryElement(SetAttrCategoryElement setAttrCategoryElement) {
        this.setAttrCategoryElement = setAttrCategoryElement;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_set_rev", nullable=false)
    public SetSpecVer getSetSpecVer() {
        return this.setSpecVer;
    }
    
    public void setSetSpecVer(SetSpecVer setSpecVer) {
        this.setSpecVer = setSpecVer;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_category", insertable=false, updatable=false)
    public SetAttrCategory getSetAttrCategory() {
        return this.setAttrCategory;
    }
    
    public void setSetAttrCategory(SetAttrCategory setAttrCategory) {
        this.setAttrCategory = setAttrCategory;
    }




}


