package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SetData generated by hbm2java
 */
@Entity
@Table(name="set_data"
    , uniqueConstraints = @UniqueConstraint(columnNames={"id_set_spec", "id_tuple"}) 
)
public class SetData  implements java.io.Serializable {


     private Integer idSet;
     private Tuple tuple;
     private SetSpec setSpec;
     private Set<MembersDictionary> membersDictionaries = new HashSet<MembersDictionary>(0);
     private Set<SetMember> setMembers = new HashSet<SetMember>(0);

    public SetData() {
    }

	
    public SetData(SetSpec setSpec) {
        this.setSpec = setSpec;
    }
    public SetData(Tuple tuple, SetSpec setSpec, Set<MembersDictionary> membersDictionaries, Set<SetMember> setMembers) {
       this.tuple = tuple;
       this.setSpec = setSpec;
       this.membersDictionaries = membersDictionaries;
       this.setMembers = setMembers;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__JPA_SET_DATA__ID_JPA_SET_DATA")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_set", unique=true, nullable=false)
    public Integer getIdSet() {
        return this.idSet;
    }
    
    public void setIdSet(Integer idSet) {
        this.idSet = idSet;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tuple")
    public Tuple getTuple() {
        return this.tuple;
    }
    
    public void setTuple(Tuple tuple) {
        this.tuple = tuple;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_set_spec", nullable=false)
    public SetSpec getSetSpec() {
        return this.setSpec;
    }
    
    public void setSetSpec(SetSpec setSpec) {
        this.setSpec = setSpec;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="setData")
    public Set<MembersDictionary> getMembersDictionaries() {
        return this.membersDictionaries;
    }
    
    public void setMembersDictionaries(Set<MembersDictionary> membersDictionaries) {
        this.membersDictionaries = membersDictionaries;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="setData")
    public Set<SetMember> getSetMembers() {
        return this.setMembers;
    }
    
    public void setSetMembers(Set<SetMember> setMembers) {
        this.setMembers = setMembers;
    }




}


