package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SetMemberViewId generated by hbm2java
 */
@Embeddable
public class SetMemberViewId  implements java.io.Serializable {


     private int idUpdate;
     private int idSet;
     private int idTuple;
     private String memberCode;

    public SetMemberViewId() {
    }

    public SetMemberViewId(int idUpdate, int idSet, int idTuple, String memberCode) {
       this.idUpdate = idUpdate;
       this.idSet = idSet;
       this.idTuple = idTuple;
       this.memberCode = memberCode;
    }
   

    @Column(name="id_update", nullable=false)
    public int getIdUpdate() {
        return this.idUpdate;
    }
    
    public void setIdUpdate(int idUpdate) {
        this.idUpdate = idUpdate;
    }

    @Column(name="id_set", nullable=false)
    public int getIdSet() {
        return this.idSet;
    }
    
    public void setIdSet(int idSet) {
        this.idSet = idSet;
    }

    @Column(name="id_tuple", nullable=false)
    public int getIdTuple() {
        return this.idTuple;
    }
    
    public void setIdTuple(int idTuple) {
        this.idTuple = idTuple;
    }

    @Column(name="member_code", nullable=false, length=20)
    public String getMemberCode() {
        return this.memberCode;
    }
    
    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SetMemberViewId) ) return false;
		 SetMemberViewId castOther = ( SetMemberViewId ) other; 
         
		 return (this.getIdUpdate()==castOther.getIdUpdate())
 && (this.getIdSet()==castOther.getIdSet())
 && (this.getIdTuple()==castOther.getIdTuple())
 && ( (this.getMemberCode()==castOther.getMemberCode()) || ( this.getMemberCode()!=null && castOther.getMemberCode()!=null && this.getMemberCode().equals(castOther.getMemberCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUpdate();
         result = 37 * result + this.getIdSet();
         result = 37 * result + this.getIdTuple();
         result = 37 * result + ( getMemberCode() == null ? 0 : this.getMemberCode().hashCode() );
         return result;
   }   


}


