package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SetMemberView generated by hbm2java
 */
@Entity
@Table(name="set_member_view"
)
public class SetMemberView  implements java.io.Serializable {


     private SetMemberViewId id;
     private ModelDataUpdate modelDataUpdate;

    public SetMemberView() {
    }

    public SetMemberView(SetMemberViewId id, ModelDataUpdate modelDataUpdate) {
       this.id = id;
       this.modelDataUpdate = modelDataUpdate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idUpdate", column=@Column(name="id_update", nullable=false) ), 
        @AttributeOverride(name="idSet", column=@Column(name="id_set", nullable=false) ), 
        @AttributeOverride(name="idTuple", column=@Column(name="id_tuple", nullable=false) ), 
        @AttributeOverride(name="memberCode", column=@Column(name="member_code", nullable=false, length=20) ) } )
    public SetMemberViewId getId() {
        return this.id;
    }
    
    public void setId(SetMemberViewId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_update", nullable=false, insertable=false, updatable=false)
    public ModelDataUpdate getModelDataUpdate() {
        return this.modelDataUpdate;
    }
    
    public void setModelDataUpdate(ModelDataUpdate modelDataUpdate) {
        this.modelDataUpdate = modelDataUpdate;
    }




}


