package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SetSpecVer generated by hbm2java
 */
@Entity
@Table(name="set_spec_ver"
    , uniqueConstraints = @UniqueConstraint(columnNames={"id_set_spec", "id_spec_rev"}) 
)
public class SetSpecVer  implements java.io.Serializable {


     private Integer idSetRev;
     private ModelSpecRev modelSpecRev;
     private SetSpec setSpec;
     private Usr usr;
     private Date creationDate;
     private int active;
     private String formula;
     private String shortDesc;
     private String longDesc;
     private Set<SetAttr> setAttrs = new HashSet<SetAttr>(0);

    public SetSpecVer() {
    }

	
    public SetSpecVer(Usr usr, Date creationDate, int active) {
        this.usr = usr;
        this.creationDate = creationDate;
        this.active = active;
    }
    public SetSpecVer(ModelSpecRev modelSpecRev, SetSpec setSpec, Usr usr, Date creationDate, int active, String formula, String shortDesc, String longDesc, Set<SetAttr> setAttrs) {
       this.modelSpecRev = modelSpecRev;
       this.setSpec = setSpec;
       this.usr = usr;
       this.creationDate = creationDate;
       this.active = active;
       this.formula = formula;
       this.shortDesc = shortDesc;
       this.longDesc = longDesc;
       this.setAttrs = setAttrs;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__JPA_SET_SPEC_VER__ID_JPA_SET_SPEC_VER")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_set_rev", unique=true, nullable=false)
    public Integer getIdSetRev() {
        return this.idSetRev;
    }
    
    public void setIdSetRev(Integer idSetRev) {
        this.idSetRev = idSetRev;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_spec_rev")
    public ModelSpecRev getModelSpecRev() {
        return this.modelSpecRev;
    }
    
    public void setModelSpecRev(ModelSpecRev modelSpecRev) {
        this.modelSpecRev = modelSpecRev;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_set_spec")
    public SetSpec getSetSpec() {
        return this.setSpec;
    }
    
    public void setSetSpec(SetSpec setSpec) {
        this.setSpec = setSpec;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="created_by", nullable=false)
    public Usr getUsr() {
        return this.usr;
    }
    
    public void setUsr(Usr usr) {
        this.usr = usr;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", nullable=false, length=29)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    
    @Column(name="active", nullable=false)
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }
    
    @Column(name="formula", length=1000)
    public String getFormula() {
        return this.formula;
    }
    
    public void setFormula(String formula) {
        this.formula = formula;
    }
    
    @Column(name="short_desc", length=20)
    public String getShortDesc() {
        return this.shortDesc;
    }
    
    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
    }
    
    @Column(name="long_desc", length=1000)
    public String getLongDesc() {
        return this.longDesc;
    }
    
    public void setLongDesc(String longDesc) {
        this.longDesc = longDesc;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="setSpecVer")
    public Set<SetAttr> getSetAttrs() {
        return this.setAttrs;
    }
    
    public void setSetAttrs(Set<SetAttr> setAttrs) {
        this.setAttrs = setAttrs;
    }




}


