package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Solver generated by hbm2java
 */
@Entity
@Table(name="solver"
)
public class Solver  implements java.io.Serializable {


     private Integer idSolver;
     private String name;
     private Set<ComputationalTask> computationalTasks = new HashSet<ComputationalTask>(0);

    public Solver() {
    }

	
    public Solver(String name) {
        this.name = name;
    }
    public Solver(String name, Set<ComputationalTask> computationalTasks) {
       this.name = name;
       this.computationalTasks = computationalTasks;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__JPA_SOLVER__ID_JPA_SOLVER")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_solver", unique=true, nullable=false)
    public Integer getIdSolver() {
        return this.idSolver;
    }
    
    public void setIdSolver(Integer idSolver) {
        this.idSolver = idSolver;
    }
    
    @Column(name="name", nullable=false, length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="solver")
    public Set<ComputationalTask> getComputationalTasks() {
        return this.computationalTasks;
    }
    
    public void setComputationalTasks(Set<ComputationalTask> computationalTasks) {
        this.computationalTasks = computationalTasks;
    }




}


