package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SpecState generated by hbm2java
 */
@Entity
@Table(name="spec_state"
)
public class SpecState  implements java.io.Serializable {


     private int idSpecState;
     private String stateName;
     private Set<ModelSpecRev> modelSpecRevs = new HashSet<ModelSpecRev>(0);

    public SpecState() {
    }

	
    public SpecState(int idSpecState, String stateName) {
        this.idSpecState = idSpecState;
        this.stateName = stateName;
    }
    public SpecState(int idSpecState, String stateName, Set<ModelSpecRev> modelSpecRevs) {
       this.idSpecState = idSpecState;
       this.stateName = stateName;
       this.modelSpecRevs = modelSpecRevs;
    }
   
     @Id 
    
    @Column(name="id_spec_state", unique=true, nullable=false)
    public int getIdSpecState() {
        return this.idSpecState;
    }
    
    public void setIdSpecState(int idSpecState) {
        this.idSpecState = idSpecState;
    }
    
    @Column(name="state_name", nullable=false, length=20)
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="specState")
    public Set<ModelSpecRev> getModelSpecRevs() {
        return this.modelSpecRevs;
    }
    
    public void setModelSpecRevs(Set<ModelSpecRev> modelSpecRevs) {
        this.modelSpecRevs = modelSpecRevs;
    }




}


