package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Srvc generated by hbm2java
 */
@Entity
@Table(name="srvc"
)
public class Srvc  implements java.io.Serializable {


     private Short idSrvc;
     private String fncAcsPth;
     private Set<LblLclLg> lblLclLgs = new HashSet<LblLclLg>(0);
     private Set<UsrGrpLg> usrGrpLgs = new HashSet<UsrGrpLg>(0);
     private Set<UsrLg> usrLgs = new HashSet<UsrLg>(0);
     private Set<LblLg> lblLgs = new HashSet<LblLg>(0);
     private Set<MsgLclLg> msgLclLgs = new HashSet<MsgLclLg>(0);
     private Set<AcsLg> acsLgs = new HashSet<AcsLg>(0);
     private Set<MsgLg> msgLgs = new HashSet<MsgLg>(0);
     private Set<UsrGrpGrpLg> usrGrpGrpLgs = new HashSet<UsrGrpGrpLg>(0);

    public Srvc() {
    }

    public Srvc(String fncAcsPth, Set<LblLclLg> lblLclLgs, Set<UsrGrpLg> usrGrpLgs, Set<UsrLg> usrLgs, Set<LblLg> lblLgs, Set<MsgLclLg> msgLclLgs, Set<AcsLg> acsLgs, Set<MsgLg> msgLgs, Set<UsrGrpGrpLg> usrGrpGrpLgs) {
       this.fncAcsPth = fncAcsPth;
       this.lblLclLgs = lblLclLgs;
       this.usrGrpLgs = usrGrpLgs;
       this.usrLgs = usrLgs;
       this.lblLgs = lblLgs;
       this.msgLclLgs = msgLclLgs;
       this.acsLgs = acsLgs;
       this.msgLgs = msgLgs;
       this.usrGrpGrpLgs = usrGrpGrpLgs;
    }
   
     @SequenceGenerator(name="generator", sequenceName="seq__srvc__id_srvc")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_srvc", unique=true, nullable=false)
    public Short getIdSrvc() {
        return this.idSrvc;
    }
    
    public void setIdSrvc(Short idSrvc) {
        this.idSrvc = idSrvc;
    }
    
    @Column(name="fnc_acs_pth", length=1024)
    public String getFncAcsPth() {
        return this.fncAcsPth;
    }
    
    public void setFncAcsPth(String fncAcsPth) {
        this.fncAcsPth = fncAcsPth;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="srvc")
    public Set<LblLclLg> getLblLclLgs() {
        return this.lblLclLgs;
    }
    
    public void setLblLclLgs(Set<LblLclLg> lblLclLgs) {
        this.lblLclLgs = lblLclLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="srvc")
    public Set<UsrGrpLg> getUsrGrpLgs() {
        return this.usrGrpLgs;
    }
    
    public void setUsrGrpLgs(Set<UsrGrpLg> usrGrpLgs) {
        this.usrGrpLgs = usrGrpLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="srvc")
    public Set<UsrLg> getUsrLgs() {
        return this.usrLgs;
    }
    
    public void setUsrLgs(Set<UsrLg> usrLgs) {
        this.usrLgs = usrLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="srvc")
    public Set<LblLg> getLblLgs() {
        return this.lblLgs;
    }
    
    public void setLblLgs(Set<LblLg> lblLgs) {
        this.lblLgs = lblLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="srvc")
    public Set<MsgLclLg> getMsgLclLgs() {
        return this.msgLclLgs;
    }
    
    public void setMsgLclLgs(Set<MsgLclLg> msgLclLgs) {
        this.msgLclLgs = msgLclLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="srvc")
    public Set<AcsLg> getAcsLgs() {
        return this.acsLgs;
    }
    
    public void setAcsLgs(Set<AcsLg> acsLgs) {
        this.acsLgs = acsLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="srvc")
    public Set<MsgLg> getMsgLgs() {
        return this.msgLgs;
    }
    
    public void setMsgLgs(Set<MsgLg> msgLgs) {
        this.msgLgs = msgLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="srvc")
    public Set<UsrGrpGrpLg> getUsrGrpGrpLgs() {
        return this.usrGrpGrpLgs;
    }
    
    public void setUsrGrpGrpLgs(Set<UsrGrpGrpLg> usrGrpGrpLgs) {
        this.usrGrpGrpLgs = usrGrpGrpLgs;
    }




}


