package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SubmodelId generated by hbm2java
 */
@Embeddable
public class SubmodelId  implements java.io.Serializable {


     private int idModel;
     private int idSubmodel;

    public SubmodelId() {
    }

    public SubmodelId(int idModel, int idSubmodel) {
       this.idModel = idModel;
       this.idSubmodel = idSubmodel;
    }
   

    @Column(name="id_model", nullable=false)
    public int getIdModel() {
        return this.idModel;
    }
    
    public void setIdModel(int idModel) {
        this.idModel = idModel;
    }

    @Column(name="id_submodel", nullable=false)
    public int getIdSubmodel() {
        return this.idSubmodel;
    }
    
    public void setIdSubmodel(int idSubmodel) {
        this.idSubmodel = idSubmodel;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SubmodelId) ) return false;
		 SubmodelId castOther = ( SubmodelId ) other; 
         
		 return (this.getIdModel()==castOther.getIdModel())
 && (this.getIdSubmodel()==castOther.getIdSubmodel());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdModel();
         result = 37 * result + this.getIdSubmodel();
         return result;
   }   


}


