package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Submodel generated by hbm2java
 */
@Entity
@Table(name="submodel"
)
public class Submodel  implements java.io.Serializable {


     private SubmodelId id;
     private Model model;
     private int position;
     private Set<ActiveEntity> activeEntities = new HashSet<ActiveEntity>(0);
     private Set<ActiveSet> activeSets = new HashSet<ActiveSet>(0);
     private Set<Comments> commentses = new HashSet<Comments>(0);

    public Submodel() {
    }

	
    public Submodel(SubmodelId id, Model model, int position) {
        this.id = id;
        this.model = model;
        this.position = position;
    }
    public Submodel(SubmodelId id, Model model, int position, Set<ActiveEntity> activeEntities, Set<ActiveSet> activeSets, Set<Comments> commentses) {
       this.id = id;
       this.model = model;
       this.position = position;
       this.activeEntities = activeEntities;
       this.activeSets = activeSets;
       this.commentses = commentses;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idModel", column=@Column(name="id_model", nullable=false) ), 
        @AttributeOverride(name="idSubmodel", column=@Column(name="id_submodel", nullable=false) ) } )
    public SubmodelId getId() {
        return this.id;
    }
    
    public void setId(SubmodelId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_model", nullable=false, insertable=false, updatable=false)
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }
    
    @Column(name="position", nullable=false)
    public int getPosition() {
        return this.position;
    }
    
    public void setPosition(int position) {
        this.position = position;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="submodel")
    public Set<ActiveEntity> getActiveEntities() {
        return this.activeEntities;
    }
    
    public void setActiveEntities(Set<ActiveEntity> activeEntities) {
        this.activeEntities = activeEntities;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="submodel")
    public Set<ActiveSet> getActiveSets() {
        return this.activeSets;
    }
    
    public void setActiveSets(Set<ActiveSet> activeSets) {
        this.activeSets = activeSets;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="submodel")
    public Set<Comments> getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }




}


