package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TermEntityId generated by hbm2java
 */
@Embeddable
public class TermEntityId  implements java.io.Serializable {


     private int idTerm;
     private int idEntitySpec;
     private int sequence;

    public TermEntityId() {
    }

    public TermEntityId(int idTerm, int idEntitySpec, int sequence) {
       this.idTerm = idTerm;
       this.idEntitySpec = idEntitySpec;
       this.sequence = sequence;
    }
   

    @Column(name="id_term", nullable=false)
    public int getIdTerm() {
        return this.idTerm;
    }
    
    public void setIdTerm(int idTerm) {
        this.idTerm = idTerm;
    }

    @Column(name="id_entity_spec", nullable=false)
    public int getIdEntitySpec() {
        return this.idEntitySpec;
    }
    
    public void setIdEntitySpec(int idEntitySpec) {
        this.idEntitySpec = idEntitySpec;
    }

    @Column(name="sequence", nullable=false)
    public int getSequence() {
        return this.sequence;
    }
    
    public void setSequence(int sequence) {
        this.sequence = sequence;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TermEntityId) ) return false;
		 TermEntityId castOther = ( TermEntityId ) other; 
         
		 return (this.getIdTerm()==castOther.getIdTerm())
 && (this.getIdEntitySpec()==castOther.getIdEntitySpec())
 && (this.getSequence()==castOther.getSequence());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTerm();
         result = 37 * result + this.getIdEntitySpec();
         result = 37 * result + this.getSequence();
         return result;
   }   


}


