package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TupleElementId generated by hbm2java
 */
@Embeddable
public class TupleElementId  implements java.io.Serializable {


     private int idTuple;
     private int idMember;
     private int position;

    public TupleElementId() {
    }

    public TupleElementId(int idTuple, int idMember, int position) {
       this.idTuple = idTuple;
       this.idMember = idMember;
       this.position = position;
    }
   

    @Column(name="id_tuple", nullable=false)
    public int getIdTuple() {
        return this.idTuple;
    }
    
    public void setIdTuple(int idTuple) {
        this.idTuple = idTuple;
    }

    @Column(name="id_member", nullable=false)
    public int getIdMember() {
        return this.idMember;
    }
    
    public void setIdMember(int idMember) {
        this.idMember = idMember;
    }

    @Column(name="position", nullable=false)
    public int getPosition() {
        return this.position;
    }
    
    public void setPosition(int position) {
        this.position = position;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TupleElementId) ) return false;
		 TupleElementId castOther = ( TupleElementId ) other; 
         
		 return (this.getIdTuple()==castOther.getIdTuple())
 && (this.getIdMember()==castOther.getIdMember())
 && (this.getPosition()==castOther.getPosition());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTuple();
         result = 37 * result + this.getIdMember();
         result = 37 * result + this.getPosition();
         return result;
   }   


}


