package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TupleElement generated by hbm2java
 */
@Entity
@Table(name="tuple_element"
)
public class TupleElement  implements java.io.Serializable {


     private TupleElementId id;
     private Tuple tuple;
     private MembersDictionary membersDictionary;

    public TupleElement() {
    }

    public TupleElement(TupleElementId id, Tuple tuple, MembersDictionary membersDictionary) {
       this.id = id;
       this.tuple = tuple;
       this.membersDictionary = membersDictionary;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idTuple", column=@Column(name="id_tuple", nullable=false) ), 
        @AttributeOverride(name="idMember", column=@Column(name="id_member", nullable=false) ), 
        @AttributeOverride(name="position", column=@Column(name="position", nullable=false) ) } )
    public TupleElementId getId() {
        return this.id;
    }
    
    public void setId(TupleElementId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tuple", nullable=false, insertable=false, updatable=false)
    public Tuple getTuple() {
        return this.tuple;
    }
    
    public void setTuple(Tuple tuple) {
        this.tuple = tuple;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_member", nullable=false, insertable=false, updatable=false)
    public MembersDictionary getMembersDictionary() {
        return this.membersDictionary;
    }
    
    public void setMembersDictionary(MembersDictionary membersDictionary) {
        this.membersDictionary = membersDictionary;
    }




}


