package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * UploadedSet generated by hbm2java
 */
@Entity
@Table(name="uploaded_set"
)
public class UploadedSet  implements java.io.Serializable {


     private Integer idUploadedSet;
     private FileUploadInfo fileUploadInfo;
     private SetSpec setSpec;

    public UploadedSet() {
    }

    public UploadedSet(FileUploadInfo fileUploadInfo, SetSpec setSpec) {
       this.fileUploadInfo = fileUploadInfo;
       this.setSpec = setSpec;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__JPA_UPLOADED_SET__ID_JPA_UPLOADED_SET")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_uploaded_set", unique=true, nullable=false)
    public Integer getIdUploadedSet() {
        return this.idUploadedSet;
    }
    
    public void setIdUploadedSet(Integer idUploadedSet) {
        this.idUploadedSet = idUploadedSet;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_file_upload")
    public FileUploadInfo getFileUploadInfo() {
        return this.fileUploadInfo;
    }
    
    public void setFileUploadInfo(FileUploadInfo fileUploadInfo) {
        this.fileUploadInfo = fileUploadInfo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_set_spec")
    public SetSpec getSetSpec() {
        return this.setSpec;
    }
    
    public void setSetSpec(SetSpec setSpec) {
        this.setSpec = setSpec;
    }




}


