package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * UploadedEntity generated by hbm2java
 */
@Entity
@Table(name="uploaded_entity"
)
public class UploadedEntity  implements java.io.Serializable {


     private Integer idUploadedEntity;
     private FileUploadInfo fileUploadInfo;
     private EntitySpec entitySpec;

    public UploadedEntity() {
    }

    public UploadedEntity(FileUploadInfo fileUploadInfo, EntitySpec entitySpec) {
       this.fileUploadInfo = fileUploadInfo;
       this.entitySpec = entitySpec;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEQ__JPA_UPLOADED_ENTITY__ID_JPA_UPLOADED_ENTITY")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_uploaded_entity", unique=true, nullable=false)
    public Integer getIdUploadedEntity() {
        return this.idUploadedEntity;
    }
    
    public void setIdUploadedEntity(Integer idUploadedEntity) {
        this.idUploadedEntity = idUploadedEntity;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_file_upload")
    public FileUploadInfo getFileUploadInfo() {
        return this.fileUploadInfo;
    }
    
    public void setFileUploadInfo(FileUploadInfo fileUploadInfo) {
        this.fileUploadInfo = fileUploadInfo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_entity_spec")
    public EntitySpec getEntitySpec() {
        return this.entitySpec;
    }
    
    public void setEntitySpec(EntitySpec entitySpec) {
        this.entitySpec = entitySpec;
    }




}


