package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Usr generated by hbm2java
 */
@Entity
@Table(name="usr"
    , uniqueConstraints = {@UniqueConstraint(columnNames="login"), @UniqueConstraint(columnNames="obj")} 
)
public class Usr  implements java.io.Serializable {


     private Integer idUsr;
     private Sn snByLckSts;
     private DbSts dbSts;
     private Athntctn athntctn;
     private Sn snBySn;
     private String login;
     private Date activate;
     private Date expire;
     private Boolean isDisabled;
     private Integer obj;
     private Set<ModelAnalysis> modelAnalysises = new HashSet<ModelAnalysis>(0);
     private Set<ComputationalTask> computationalTasks = new HashSet<ComputationalTask>(0);
     private Set<ModelInstance> modelInstances = new HashSet<ModelInstance>(0);
     private Set<UsrLg> usrLgs = new HashSet<UsrLg>(0);
     private Set<Model> modelsForCreatedBy = new HashSet<Model>(0);
     private Set<UsrGrp> usrGrps = new HashSet<UsrGrp>(0);
     private Set<Sn> sns = new HashSet<Sn>(0);
     private Set<AthntctnUsr> athntctnUsrs = new HashSet<AthntctnUsr>(0);
     private Set<UsrGrp> usrGrps_1 = new HashSet<UsrGrp>(0);
     private Set<EntitySpecVer> entitySpecVers = new HashSet<EntitySpecVer>(0);
     private Set<SetSpecVer> setSpecVers = new HashSet<SetSpecVer>(0);
     private Set<Model> modelsForModifiedBy = new HashSet<Model>(0);
     private Set<ModelSpecRev> modelSpecRevsForCreatedBy = new HashSet<ModelSpecRev>(0);
     private Set<ModelDataUpdate> modelDataUpdates = new HashSet<ModelDataUpdate>(0);
     private Set<ModelSpecRev> modelSpecRevsForModifiedBy = new HashSet<ModelSpecRev>(0);
     private Set<ModelSpecRev> modelSpecRevsForCommitedBy = new HashSet<ModelSpecRev>(0);

    public Usr() {
    }

	
    public Usr(DbSts dbSts, Sn snBySn, String login) {
        this.dbSts = dbSts;
        this.snBySn = snBySn;
        this.login = login;
    }
    public Usr(Sn snByLckSts, DbSts dbSts, Athntctn athntctn, Sn snBySn, String login, Date activate, Date expire, Boolean isDisabled, Integer obj, Set<ModelAnalysis> modelAnalysises, Set<ComputationalTask> computationalTasks, Set<ModelInstance> modelInstances, Set<UsrLg> usrLgs, Set<Model> modelsForCreatedBy, Set<UsrGrp> usrGrps, Set<Sn> sns, Set<AthntctnUsr> athntctnUsrs, Set<UsrGrp> usrGrps_1, Set<EntitySpecVer> entitySpecVers, Set<SetSpecVer> setSpecVers, Set<Model> modelsForModifiedBy, Set<ModelSpecRev> modelSpecRevsForCreatedBy, Set<ModelDataUpdate> modelDataUpdates, Set<ModelSpecRev> modelSpecRevsForModifiedBy, Set<ModelSpecRev> modelSpecRevsForCommitedBy) {
       this.snByLckSts = snByLckSts;
       this.dbSts = dbSts;
       this.athntctn = athntctn;
       this.snBySn = snBySn;
       this.login = login;
       this.activate = activate;
       this.expire = expire;
       this.isDisabled = isDisabled;
       this.obj = obj;
       this.modelAnalysises = modelAnalysises;
       this.computationalTasks = computationalTasks;
       this.modelInstances = modelInstances;
       this.usrLgs = usrLgs;
       this.modelsForCreatedBy = modelsForCreatedBy;
       this.usrGrps = usrGrps;
       this.sns = sns;
       this.athntctnUsrs = athntctnUsrs;
       this.usrGrps_1 = usrGrps_1;
       this.entitySpecVers = entitySpecVers;
       this.setSpecVers = setSpecVers;
       this.modelsForModifiedBy = modelsForModifiedBy;
       this.modelSpecRevsForCreatedBy = modelSpecRevsForCreatedBy;
       this.modelDataUpdates = modelDataUpdates;
       this.modelSpecRevsForModifiedBy = modelSpecRevsForModifiedBy;
       this.modelSpecRevsForCommitedBy = modelSpecRevsForCommitedBy;
    }
   
     @SequenceGenerator(name="generator", sequenceName="seq__usr__id_usr")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id_usr", unique=true, nullable=false)
    public Integer getIdUsr() {
        return this.idUsr;
    }
    
    public void setIdUsr(Integer idUsr) {
        this.idUsr = idUsr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lck_sts")
    public Sn getSnByLckSts() {
        return this.snByLckSts;
    }
    
    public void setSnByLckSts(Sn snByLckSts) {
        this.snByLckSts = snByLckSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="athntctn")
    public Athntctn getAthntctn() {
        return this.athntctn;
    }
    
    public void setAthntctn(Athntctn athntctn) {
        this.athntctn = athntctn;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sn", nullable=false)
    public Sn getSnBySn() {
        return this.snBySn;
    }
    
    public void setSnBySn(Sn snBySn) {
        this.snBySn = snBySn;
    }
    
    @Column(name="login", unique=true, nullable=false, length=64)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="activate", length=29)
    public Date getActivate() {
        return this.activate;
    }
    
    public void setActivate(Date activate) {
        this.activate = activate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expire", length=29)
    public Date getExpire() {
        return this.expire;
    }
    
    public void setExpire(Date expire) {
        this.expire = expire;
    }
    
    @Column(name="is_disabled")
    public Boolean getIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(Boolean isDisabled) {
        this.isDisabled = isDisabled;
    }
    
    @Column(name="obj", unique=true)
    public Integer getObj() {
        return this.obj;
    }
    
    public void setObj(Integer obj) {
        this.obj = obj;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usr")
    public Set<ModelAnalysis> getModelAnalysises() {
        return this.modelAnalysises;
    }
    
    public void setModelAnalysises(Set<ModelAnalysis> modelAnalysises) {
        this.modelAnalysises = modelAnalysises;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usr")
    public Set<ComputationalTask> getComputationalTasks() {
        return this.computationalTasks;
    }
    
    public void setComputationalTasks(Set<ComputationalTask> computationalTasks) {
        this.computationalTasks = computationalTasks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usr")
    public Set<ModelInstance> getModelInstances() {
        return this.modelInstances;
    }
    
    public void setModelInstances(Set<ModelInstance> modelInstances) {
        this.modelInstances = modelInstances;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usr")
    public Set<UsrLg> getUsrLgs() {
        return this.usrLgs;
    }
    
    public void setUsrLgs(Set<UsrLg> usrLgs) {
        this.usrLgs = usrLgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usrByCreatedBy")
    public Set<Model> getModelsForCreatedBy() {
        return this.modelsForCreatedBy;
    }
    
    public void setModelsForCreatedBy(Set<Model> modelsForCreatedBy) {
        this.modelsForCreatedBy = modelsForCreatedBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usr")
    public Set<UsrGrp> getUsrGrps() {
        return this.usrGrps;
    }
    
    public void setUsrGrps(Set<UsrGrp> usrGrps) {
        this.usrGrps = usrGrps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usr")
    public Set<Sn> getSns() {
        return this.sns;
    }
    
    public void setSns(Set<Sn> sns) {
        this.sns = sns;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usr")
    public Set<AthntctnUsr> getAthntctnUsrs() {
        return this.athntctnUsrs;
    }
    
    public void setAthntctnUsrs(Set<AthntctnUsr> athntctnUsrs) {
        this.athntctnUsrs = athntctnUsrs;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usrs")
    public Set<UsrGrp> getUsrGrps_1() {
        return this.usrGrps_1;
    }
    
    public void setUsrGrps_1(Set<UsrGrp> usrGrps_1) {
        this.usrGrps_1 = usrGrps_1;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usr")
    public Set<EntitySpecVer> getEntitySpecVers() {
        return this.entitySpecVers;
    }
    
    public void setEntitySpecVers(Set<EntitySpecVer> entitySpecVers) {
        this.entitySpecVers = entitySpecVers;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usr")
    public Set<SetSpecVer> getSetSpecVers() {
        return this.setSpecVers;
    }
    
    public void setSetSpecVers(Set<SetSpecVer> setSpecVers) {
        this.setSpecVers = setSpecVers;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usrByModifiedBy")
    public Set<Model> getModelsForModifiedBy() {
        return this.modelsForModifiedBy;
    }
    
    public void setModelsForModifiedBy(Set<Model> modelsForModifiedBy) {
        this.modelsForModifiedBy = modelsForModifiedBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usrByCreatedBy")
    public Set<ModelSpecRev> getModelSpecRevsForCreatedBy() {
        return this.modelSpecRevsForCreatedBy;
    }
    
    public void setModelSpecRevsForCreatedBy(Set<ModelSpecRev> modelSpecRevsForCreatedBy) {
        this.modelSpecRevsForCreatedBy = modelSpecRevsForCreatedBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usr")
    public Set<ModelDataUpdate> getModelDataUpdates() {
        return this.modelDataUpdates;
    }
    
    public void setModelDataUpdates(Set<ModelDataUpdate> modelDataUpdates) {
        this.modelDataUpdates = modelDataUpdates;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usrByModifiedBy")
    public Set<ModelSpecRev> getModelSpecRevsForModifiedBy() {
        return this.modelSpecRevsForModifiedBy;
    }
    
    public void setModelSpecRevsForModifiedBy(Set<ModelSpecRev> modelSpecRevsForModifiedBy) {
        this.modelSpecRevsForModifiedBy = modelSpecRevsForModifiedBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usrByCommitedBy")
    public Set<ModelSpecRev> getModelSpecRevsForCommitedBy() {
        return this.modelSpecRevsForCommitedBy;
    }
    
    public void setModelSpecRevsForCommitedBy(Set<ModelSpecRev> modelSpecRevsForCommitedBy) {
        this.modelSpecRevsForCommitedBy = modelSpecRevsForCommitedBy;
    }




}


