package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UsrGrpLg generated by hbm2java
 */
@Entity
@Table(name="usr_grp_lg"
    , uniqueConstraints = @UniqueConstraint(columnNames="obj") 
)
public class UsrGrpLg  implements java.io.Serializable {


     private UsrGrpLgId id;
     private Srvc srvc;
     private Sn snByLckSts;
     private UsrGrp usrGrp;
     private DbSts dbSts;
     private Lbl lbl;
     private Sn snBySn;
     private Integer usr;
     private Integer obj;

    public UsrGrpLg() {
    }

	
    public UsrGrpLg(UsrGrpLgId id, Srvc srvc, UsrGrp usrGrp, DbSts dbSts, Lbl lbl, Sn snBySn) {
        this.id = id;
        this.srvc = srvc;
        this.usrGrp = usrGrp;
        this.dbSts = dbSts;
        this.lbl = lbl;
        this.snBySn = snBySn;
    }
    public UsrGrpLg(UsrGrpLgId id, Srvc srvc, Sn snByLckSts, UsrGrp usrGrp, DbSts dbSts, Lbl lbl, Sn snBySn, Integer usr, Integer obj) {
       this.id = id;
       this.srvc = srvc;
       this.snByLckSts = snByLckSts;
       this.usrGrp = usrGrp;
       this.dbSts = dbSts;
       this.lbl = lbl;
       this.snBySn = snBySn;
       this.usr = usr;
       this.obj = obj;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idLg", column=@Column(name="id_lg", nullable=false) ), 
        @AttributeOverride(name="ts", column=@Column(name="ts", nullable=false, length=13) ) } )
    public UsrGrpLgId getId() {
        return this.id;
    }
    
    public void setId(UsrGrpLgId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="srvc", nullable=false)
    public Srvc getSrvc() {
        return this.srvc;
    }
    
    public void setSrvc(Srvc srvc) {
        this.srvc = srvc;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lck_sts")
    public Sn getSnByLckSts() {
        return this.snByLckSts;
    }
    
    public void setSnByLckSts(Sn snByLckSts) {
        this.snByLckSts = snByLckSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usr_grp", nullable=false)
    public UsrGrp getUsrGrp() {
        return this.usrGrp;
    }
    
    public void setUsrGrp(UsrGrp usrGrp) {
        this.usrGrp = usrGrp;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lbl", nullable=false)
    public Lbl getLbl() {
        return this.lbl;
    }
    
    public void setLbl(Lbl lbl) {
        this.lbl = lbl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sn", nullable=false)
    public Sn getSnBySn() {
        return this.snBySn;
    }
    
    public void setSnBySn(Sn snBySn) {
        this.snBySn = snBySn;
    }
    
    @Column(name="usr")
    public Integer getUsr() {
        return this.usr;
    }
    
    public void setUsr(Integer usr) {
        this.usr = usr;
    }
    
    @Column(name="obj", unique=true)
    public Integer getObj() {
        return this.obj;
    }
    
    public void setObj(Integer obj) {
        this.obj = obj;
    }




}


