package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsrGrpGrpId generated by hbm2java
 */
@Embeddable
public class UsrGrpGrpId  implements java.io.Serializable {


     private short idUsrGrp;
     private short idUsrGrpMbr;

    public UsrGrpGrpId() {
    }

    public UsrGrpGrpId(short idUsrGrp, short idUsrGrpMbr) {
       this.idUsrGrp = idUsrGrp;
       this.idUsrGrpMbr = idUsrGrpMbr;
    }
   

    @Column(name="id_usr_grp", nullable=false)
    public short getIdUsrGrp() {
        return this.idUsrGrp;
    }
    
    public void setIdUsrGrp(short idUsrGrp) {
        this.idUsrGrp = idUsrGrp;
    }

    @Column(name="id_usr_grp_mbr", nullable=false)
    public short getIdUsrGrpMbr() {
        return this.idUsrGrpMbr;
    }
    
    public void setIdUsrGrpMbr(short idUsrGrpMbr) {
        this.idUsrGrpMbr = idUsrGrpMbr;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsrGrpGrpId) ) return false;
		 UsrGrpGrpId castOther = ( UsrGrpGrpId ) other; 
         
		 return (this.getIdUsrGrp()==castOther.getIdUsrGrp())
 && (this.getIdUsrGrpMbr()==castOther.getIdUsrGrpMbr());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUsrGrp();
         result = 37 * result + this.getIdUsrGrpMbr();
         return result;
   }   


}


