package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UsrGrpGrp generated by hbm2java
 */
@Entity
@Table(name="usr_grp_grp"
)
public class UsrGrpGrp  implements java.io.Serializable {


     private UsrGrpGrpId id;
     private UsrGrp usrGrpByIdUsrGrp;
     private UsrGrp usrGrpByIdUsrGrpMbr;
     private DbSts dbSts;
     private Sn sn;
     private Set<UsrGrpGrpLg> usrGrpGrpLgs = new HashSet<UsrGrpGrpLg>(0);

    public UsrGrpGrp() {
    }

	
    public UsrGrpGrp(UsrGrpGrpId id, UsrGrp usrGrpByIdUsrGrp, UsrGrp usrGrpByIdUsrGrpMbr, DbSts dbSts, Sn sn) {
        this.id = id;
        this.usrGrpByIdUsrGrp = usrGrpByIdUsrGrp;
        this.usrGrpByIdUsrGrpMbr = usrGrpByIdUsrGrpMbr;
        this.dbSts = dbSts;
        this.sn = sn;
    }
    public UsrGrpGrp(UsrGrpGrpId id, UsrGrp usrGrpByIdUsrGrp, UsrGrp usrGrpByIdUsrGrpMbr, DbSts dbSts, Sn sn, Set<UsrGrpGrpLg> usrGrpGrpLgs) {
       this.id = id;
       this.usrGrpByIdUsrGrp = usrGrpByIdUsrGrp;
       this.usrGrpByIdUsrGrpMbr = usrGrpByIdUsrGrpMbr;
       this.dbSts = dbSts;
       this.sn = sn;
       this.usrGrpGrpLgs = usrGrpGrpLgs;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idUsrGrp", column=@Column(name="id_usr_grp", nullable=false) ), 
        @AttributeOverride(name="idUsrGrpMbr", column=@Column(name="id_usr_grp_mbr", nullable=false) ) } )
    public UsrGrpGrpId getId() {
        return this.id;
    }
    
    public void setId(UsrGrpGrpId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usr_grp", nullable=false, insertable=false, updatable=false)
    public UsrGrp getUsrGrpByIdUsrGrp() {
        return this.usrGrpByIdUsrGrp;
    }
    
    public void setUsrGrpByIdUsrGrp(UsrGrp usrGrpByIdUsrGrp) {
        this.usrGrpByIdUsrGrp = usrGrpByIdUsrGrp;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usr_grp_mbr", nullable=false, insertable=false, updatable=false)
    public UsrGrp getUsrGrpByIdUsrGrpMbr() {
        return this.usrGrpByIdUsrGrpMbr;
    }
    
    public void setUsrGrpByIdUsrGrpMbr(UsrGrp usrGrpByIdUsrGrpMbr) {
        this.usrGrpByIdUsrGrpMbr = usrGrpByIdUsrGrpMbr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sn", nullable=false)
    public Sn getSn() {
        return this.sn;
    }
    
    public void setSn(Sn sn) {
        this.sn = sn;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usrGrpGrp")
    public Set<UsrGrpGrpLg> getUsrGrpGrpLgs() {
        return this.usrGrpGrpLgs;
    }
    
    public void setUsrGrpGrpLgs(Set<UsrGrpGrpLg> usrGrpGrpLgs) {
        this.usrGrpGrpLgs = usrGrpGrpLgs;
    }




}


