package at.ac.iiasa.ime.enrima.domain;
// Generated Nov 29, 2011 9:34:07 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsrLg generated by hbm2java
 */
@Entity
@Table(name="usr_lg"
)
public class UsrLg  implements java.io.Serializable {


     private UsrLgId id;
     private Srvc srvc;
     private Sn snByLckSts;
     private Usr usr;
     private DbSts dbSts;
     private Athntctn athntctn;
     private Sn snBySn;
     private String login;
     private Date activate;
     private Date expire;
     private Boolean isDisabled;
     private Integer obj;

    public UsrLg() {
    }

	
    public UsrLg(UsrLgId id, Srvc srvc, Usr usr, DbSts dbSts, Sn snBySn) {
        this.id = id;
        this.srvc = srvc;
        this.usr = usr;
        this.dbSts = dbSts;
        this.snBySn = snBySn;
    }
    public UsrLg(UsrLgId id, Srvc srvc, Sn snByLckSts, Usr usr, DbSts dbSts, Athntctn athntctn, Sn snBySn, String login, Date activate, Date expire, Boolean isDisabled, Integer obj) {
       this.id = id;
       this.srvc = srvc;
       this.snByLckSts = snByLckSts;
       this.usr = usr;
       this.dbSts = dbSts;
       this.athntctn = athntctn;
       this.snBySn = snBySn;
       this.login = login;
       this.activate = activate;
       this.expire = expire;
       this.isDisabled = isDisabled;
       this.obj = obj;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idLg", column=@Column(name="id_lg", nullable=false) ), 
        @AttributeOverride(name="ts", column=@Column(name="ts", nullable=false, length=29) ) } )
    public UsrLgId getId() {
        return this.id;
    }
    
    public void setId(UsrLgId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="srvc", nullable=false)
    public Srvc getSrvc() {
        return this.srvc;
    }
    
    public void setSrvc(Srvc srvc) {
        this.srvc = srvc;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lck_sts")
    public Sn getSnByLckSts() {
        return this.snByLckSts;
    }
    
    public void setSnByLckSts(Sn snByLckSts) {
        this.snByLckSts = snByLckSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usr", nullable=false)
    public Usr getUsr() {
        return this.usr;
    }
    
    public void setUsr(Usr usr) {
        this.usr = usr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="db_sts", nullable=false)
    public DbSts getDbSts() {
        return this.dbSts;
    }
    
    public void setDbSts(DbSts dbSts) {
        this.dbSts = dbSts;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="athntctn")
    public Athntctn getAthntctn() {
        return this.athntctn;
    }
    
    public void setAthntctn(Athntctn athntctn) {
        this.athntctn = athntctn;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sn", nullable=false)
    public Sn getSnBySn() {
        return this.snBySn;
    }
    
    public void setSnBySn(Sn snBySn) {
        this.snBySn = snBySn;
    }
    
    @Column(name="login", length=64)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="activate", length=29)
    public Date getActivate() {
        return this.activate;
    }
    
    public void setActivate(Date activate) {
        this.activate = activate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expire", length=29)
    public Date getExpire() {
        return this.expire;
    }
    
    public void setExpire(Date expire) {
        this.expire = expire;
    }
    
    @Column(name="is_disabled")
    public Boolean getIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(Boolean isDisabled) {
        this.isDisabled = isDisabled;
    }
    
    @Column(name="obj")
    public Integer getObj() {
        return this.obj;
    }
    
    public void setObj(Integer obj) {
        this.obj = obj;
    }




}


